growingio/gio-design

packages/components/src/components/link/style/index.less, packages/components/src/components/radio/style/index.less, packages/components/src/components/sign/style/index.less, packages/components/src/stylesheet/index.less, packages/tokens/properties/color/background.json, packages/tokens/properties/color/border.json, packages/tokens/properties/color/text.json, packages/tokens/properties/palette.json, yarn.lock
=> refactor(components): update palette and othe tokens

packages/components/src/components/checkbox/style/index.less, packages/website/src/components/functional/dropdown/demo/base.tsx, packages/website/src/components/functional/dropdown/demo/other.tsx
| 🇺🇸 English |  align check icon when be used to Table         |
| 🇨🇳 Chinese |   修正CheckBox 被用于 Table 时”对号“ 不居中       |
=> style(checkbox): align check icon when be used to Table

packages/components/src/components/alert/alert.tsx, packages/components/src/components/alert/style/index.less
ISSUES CLOSED: #140
https://github.com/growingio/gio-design/issues/140
| 🇺🇸 English | add color on icon          |
| 🇨🇳 Chinese |  添加alert中icon的颜色         |
=> style(alert): add color on icon

packages/components/src/components/dropdown/style/index.less, packages/components/src/components/popconfirm/style/index.less, packages/components/src/components/popover/style/index.less, packages/components/src/components/table/style/index.less, packages/components/src/components/tooltip/style/index.less, packages/tokens/properties/zIndex.json
从全局角度设计一下元素的层叠展示效果。
下图是ant-design的zindex token
用到 zindex 的同学，思考其值并加入到token。
| 🇺🇸 English |  design zindex display         |
| 🇨🇳 Chinese |   设计 zindex 排列        |
=> style: design zindex display

packages/components/src/components/avatar/Avatar.tsx, packages/components/src/components/avatar/__tests__/__snapshots__/AvatarGroup.test.js.snap, packages/components/src/utils/composeRef.ts
修复avatar组件不能被Dropdown等组件触发的bug。
所有需要触发tooltip、Popconfirm、Popover、Dropdown的组件都需要解构参数，并传rest给return的元素。
| 🇺🇸 English |    fix avatar can't trigger Dropdown        |
| 🇨🇳 Chinese |  修复avatar组件不能触发Dropdown 的bug  |
=> fix(avatar): fix avatar can't trigger Dropdown

packages/components/src/components/table/Table.tsx, packages/components/src/components/table/hook/useFilter.tsx, packages/components/src/components/table/hook/usePagination.tsx, packages/components/src/components/table/hook/useSorter.tsx, packages/components/src/components/table/interface.ts, packages/components/src/components/table/style/index.less, packages/icons/src/DragMove.tsx, packages/website/src/components/functional/table/index.zh-CN.md
add rowKey, rowClassName, onRow, onHeaderRow, showHover, showHeader prop to table.
add className, onHeaderCell prop to column.
refacter style file.
key is not must set, it default use dataIndex or index.
add rowKey, rowClassName, onRow, onHeaderRow, showHover, showHeader prop to table.
add className, onHeaderCell prop to column.
key is not must set, it default use dataIndex or index.
| 🇺🇸 English |  add some prop          |
| 🇨🇳 Chinese |  table 添加一些 参数         |
=> feat(table): add some prop to table

packages/components/src/components/tooltip/Tooltip.tsx
fix children style prop be covered
| 🇺🇸 English |   fix children style prop be covered        |
| 🇨🇳 Chinese |   修复tooltip子组件style参数被覆盖问题        |
=> fix(tooltip): fix children style prop be covered

packages/components/src/components/table/style/index.less, packages/components/src/components/tooltip/Tooltip.tsx
上次重构table样式文件的时候，忘记了表体水平方向没有边框。 没有发版，不算changelog
=> style(table): fix table border style

packages/components/src/components/checkbox/style/index.less
advance .gio-checkbox-icon-indeterminate style priority
| 🇺🇸 English |  advance .gio-checkbox-icon-indeterminate style priority         |
| 🇨🇳 Chinese | 提升 .gio-checkbox-icon-indeterminate 样式优先级          |
=> style(checkbox): advance .gio-checkbox-icon-indeterminate style priority

packages/components/src/components/input/InputNumber.tsx, packages/components/src/components/input/hooks/useEnter.tsx, packages/components/src/components/input/interfaces.ts, packages/website/src/components/basic/input/demo/Input.tsx
ISSUES CLOSED: #217
#217 
value and onChange prop is optional
| 🇺🇸 English |  value and onChange prop is optional         |
| 🇨🇳 Chinese |   value和 onChange 参数是可选的        |
=> feat(input): value and onChange prop is optional

packages/components/src/components/checkbox/style/index.less, packages/components/src/components/tag/interface.ts
上次修改checkbox样式改的地方不对,fix
advance .gio-checkbox-icon-indeterminate style priority。
| 🇺🇸 English |  advance .gio-checkbox-icon-indeterminate style priority          |
| 🇨🇳 Chinese | 提升 .gio-checkbox-icon-indeterminate 样式优先级          |
=> fix(checkbox): 上次修改checkbox样式改的地方不对,fix

packages/components/src/components/select/Select.tsx, packages/website/src/components/functional/select/demos/multiple.tsx, packages/website/src/components/functional/select/demos/search.tsx, yarn.lock
=> fix(onchange bug): onchange bug

packages/components/src/components/dropdown/style/index.less, packages/website/src/components/functional/dropdown/demo/assistList.tsx, packages/website/src/components/functional/dropdown/demo/content.tsx, packages/website/src/components/functional/dropdown/demo/filter.tsx, packages/website/src/components/functional/dropdown/demo/function.tsx, packages/website/src/components/functional/dropdown/demo/index.less, packages/website/src/components/functional/dropdown/demo/placement.tsx
| 🇺🇸 English |  continue perfecting Dropdown demo         |
| 🇨🇳 Chinese |  继续完善Dropdown Demo |
=> docs(dropdown): continue perfecting Dropdown demo

packages/components/src/components/table/hook/usePagination.tsx, packages/website/src/components/functional/table/index.zh-CN.md
some state of pagination not reset when dataSource update.
when table dataSource update, all state of pagination should be reset.
| 🇺🇸 English | when table dataSource update, all state of pagination should be reset.          |
| 🇨🇳 Chinese |   当table的DataSource改变的时候，所有列表分页的状态都应该被重置。   |
=> fix(table): some state of pagination not reset when dataSource update

packages/components/src/components/dropdown/Dropdown.tsx, packages/components/src/components/dropdown/__test__/Dropdown.test.js, packages/components/src/components/dropdown/interface.ts, packages/website/src/components/functional/dropdown/demo/filter.tsx, packages/website/src/components/functional/dropdown/demo/function.tsx, packages/website/src/components/functional/dropdown/index.zh-CN.md
auto close after click overlay element.
change overlay type from ReactNode to ReactElement.
| 🇺🇸 English |    auto close after click overlay element. change overlay type from ReactNode to ReactElement.       |
| 🇨🇳 Chinese | 点击overlay元素后，自动关闭下拉菜单。将overlay的类型从ReactNode更改为ReactElement           |
=> fix(dropdown): auto close after click overlay element

packages/components/src/components/link/index.tsx, packages/components/src/components/link/interface.ts, packages/components/src/utils/type.ts
| 🇺🇸 English |      Fix type error in Link component      |
| 🇨🇳 Chinese |    修复 Link 组件中的类型问题       |
=> fix: fix link type error

packages/components/src/components/select/Select.tsx, packages/components/src/components/select/interface.ts, packages/website/src/components/basic/tooltip/index.zh-CN.md, packages/website/src/components/functional/select/index.zh-CN.md
| 🇺🇸 English |     add getContainer prop      |
| 🇨🇳 Chinese |   添加 getContainer 参数        |
=> feat(select): add getContainer prop

packages/components/src/components/table/Table.tsx, packages/components/src/components/table/Title.tsx, packages/components/src/components/table/__test__/Table.test.js, packages/components/src/components/table/hook/usePagination.tsx, packages/components/src/components/table/interface.ts
目前的逻辑是，当数据源改变 且 新的总页数小于当前页数时，分页重置到第一页。否则不重置页数。
筛选也会重置页数。
| 🇺🇸 English |  define when dataSource update, pagination behaviour         |
| 🇨🇳 Chinese | 定义当数据源改变时，分页行为          |
=> refactor(table): define when dataSource update, pagination behaviour

packages/components/src/components/date-picker/dateRangePicker.tsx, packages/components/src/components/date-picker/interface.tsx, packages/website/src/components/functional/date-picker/demo/range.tsx
add dateRangePicker disabledDate methods and fix props.value change is not change Input value
ISSUES CLOSED: #304
| 🇺🇸 English |    add dateRangePicker disabledDate methods       |
| 🇨🇳 Chinese |     RangePicker增加disabledDate方法      |
=> feat(date-picker): add dateRangePicker disabledDate methods

packages/components/src/components/select/Select.tsx, packages/components/src/components/select/interface.ts, packages/components/src/components/select/style/index.less, packages/website/src/components/functional/select/demos/options.ts, packages/website/src/components/functional/select/demos/search.tsx, packages/website/src/components/functional/select/index.zh-CN.md
需要list支持value受控 #250 
#303 
#278 
=> fix: allow use value control selections;

packages/components/src/components/upload/Upload.tsx, packages/components/src/components/upload/interface.ts, packages/components/src/components/upload/style/index.less, packages/website/src/components/functional/upload/demos/card.tsx
Upload组件增加一个可选参数successBorder，控制图片上传成功后边框是否显示，默认为false
| 🇺🇸 English |      An optional parameter successBorder is added to the upload component to control whether the border is displayed after the image is uploaded successfully. The default value is false     |
| 🇨🇳 Chinese |     Upload组件增加一个可选参数successBorder，控制图片上传成功后边框是否显示，默认为false      |
=> fix(upload): upload组件增加一个可选参数successBorder，控制图片上传成功后边框是否显示

packages/components/src/components/dropdown/Dropdown.tsx, packages/website/src/components/functional/dropdown/demo/base.tsx
修复Dropdown组件中placement方向的问题，由12个方向改为只有上下6个方向可选，默认方向为下
| 🇺🇸 English |      Fixed the placement direction problem in the Dropdown component. From 12 directions to 6 directions, the default direction is down     |
| 🇨🇳 Chinese |     修复Dropdown组件中placement方向的问题，由12个方向改为只有上下6个方向可选，默认方向为下      |
=> fix(dropdown): 修复Dropdown组件中placement方向的问题，由12个方向改为只有上下6个方向可选，默认方向为下

packages/components/src/components/select/style/index.less
=> style(select): 定义了select组件中input选择框内的文字尺寸

packages/components/package.json, packages/icons/package.json, packages/website/src/develop/changelog/components.en-US.md, packages/website/src/develop/changelog/components.zh-CN.md, packages/website/src/develop/changelog/icons.en-US.md, packages/website/src/develop/changelog/icons.zh-CN.md
- Grid
- 🆕 新增Grid组件 [#338](https://github.com/growingio/gio-design/pull/338)
- Form
- 🐛修复colon不渲染的问题 [#340](https://github.com/growingio/gio-design/pull/340)
- Dropdown
- 💄placement由12个方向改为只有上下6个方向可选，默认方向为下 [#333](https://github.com/growingio/gio-design/pull/333/)
- Upload
- 🆕增加一个可选参数successBorder，控制图片上传成功后边框是否显示 [#331](https://github.com/growingio/gio-design/pull/331)
- Select
- 💄定义了select组件中input选择框内的文字尺寸 [#337](https://github.com/growingio/gio-design/pull/337)
- 🆕 新增[#349](https://github.com/growingio/gio-design/pull/349)
- `CopyOutlined`
- `DownloadOutlined`
- `InformationCircleOutlined`
- `SequenceOutlined`
- `ShareOutlined`
=> docs(release): @gio-design/components 20.10.5 change log

packages/components/src/components/tooltip/Tooltip.tsx, packages/components/src/components/tooltip/__tests__/Tooltip.test.js, packages/components/src/components/tooltip/interface.ts, packages/website/src/components/basic/tooltip/index.zh-CN.md
ISSUES CLOSED: #332
- 文字提示
- 添加 disabled 参数
---
- Tooltip
- add disabled prop
=> feat(tooltip): add disabled prop

packages/components/src/components/popconfirm/Popconfirm.tsx, packages/components/src/components/popconfirm/interface.ts
- 气泡确认框
- 去掉跟disabled相关的代码
---
- popconfirm
- remove code associated with disabled
=> refactor(popconfirm): remove code associated with disabled

packages/components/src/components/search-bar/__tests__/__snapshots__/searchbar.test.js.snap, packages/components/src/components/search-bar/index.tsx, packages/components/src/components/search-bar/style/index.less, packages/website/src/components/functional/searchBar/demo/index.tsx
解决Search Bar组件size=large或者small的时候，右侧放大镜icon垂直方向没有居中的问题
| 🇺🇸 English |      When the search bar component size = large or small, the vertical direction of the right magnifying glass icon is not centered     |
| 🇨🇳 Chinese |     解决Search Bar组件size=large或者small的时候，右侧放大镜icon垂直方向没有居中的问题      |
=> fix(search bar): 解决Search Bar组件size=large或者small的时候，右侧放大镜icon垂直方向没有居中的问题

packages/components/package.json, packages/website/src/develop/changelog/components.en-US.md, packages/website/src/develop/changelog/components.zh-CN.md
- component
- 🆕 avatar, card类型的 Upload 支持 placeholderImg 展示 [#379](https://github.com/growingio/gio-design/pull/379)
- 🛎 StepModal 的 onNext, onBack 支持异步调用，可打断下一步的执行 [#378](https://github.com/growingio/gio-design/pull/378)
- popconfirm
- 去掉跟disabled相关的代码 [#377](https://github.com/growingio/gio-design/pull/377)
- tootip
- 🆕 新增 disabled 参数 [#367](https://github.com/growingio/gio-design/pull/367)
- input
- 🛎 修改Input组件为受控组件，以及相关website demo，unit test, 样式不再固定为300px [#374](https://github.com/growingio/gio-design/pull/374)
- Table
- 🐛 修复当Table内容为空时，鼠标hover 会变色的问题。定义当设置ellipsis时与render方法之间的关系。[#334](https://github.com/growingio/gio-design/pull/334)
=> docs(release): @gio-design/components 20.10.6 change log

packages/components/src/components/list/interface.ts, packages/components/src/components/list/list.tsx, packages/website/src/components/functional/list/index.zh-CN.md
ISSUES CLOSED: #321
- list组件
- width支持string类型
---
- Component list
- support string type of width
=> refactor(list): support string type of width in component list 

packages/components/src/components/avatar/Avatar.tsx, packages/components/src/components/avatar/AvatarGroup.tsx, packages/components/src/components/avatar/interface.ts, packages/website/src/components/functional/avatar/demo/group.tsx, packages/website/src/components/functional/avatar/index.zh-CN.md
ISSUES CLOSED: #418
- 头像
- 支持自定义气泡框内容
- 添加 style 参数
---
- Avatar 
- support custom tooltip title
- add style prop
=> feat(avatar): support custom tooltip title

packages/components/src/components/search-bar/index.tsx, packages/components/src/components/search-bar/style/index.less
let the display panel adapt to the width of input
- 搜索框
- 让展示面板自适应input的宽度，并且让提示文字在宽度过小时超出部分显示 ...
---
- Search Bar
- Let the display panel adapt to the width of input,and let the prompt text show '...' when the width is too short
=> fix(search-bar): let the display panel adapt to the width of input

packages/tokens/properties/color/background.json
affects: @gio-design/tokens
change assist button background to transparent
- 按钮
- 将assist类型的按钮背景色由白色改为透明
---
- button
- change assist button background to transparent
=> fix(button): change assist button background to transparent

packages/components/src/components/popconfirm/__tests__/Popconfirm.test.js, packages/components/src/components/popconfirm/interface.ts, packages/components/src/components/popover/__tests__/Popover.test.js
fix the stylelint and eslint error
- 气泡确认框、气泡卡片
-修复eslint错误
---
- popconfirm/popover
- fix the stylelint and eslint error
=> refactor(popconfirm/popover): fix the stylelint and eslint error

packages/components/package.json, packages/components/src/components/select/Select.tsx, packages/website/src/develop/changelog/components.en-US.md, packages/website/src/develop/changelog/components.zh-CN.md
- Select #393 
- 🆕 新增 disabled 禁用功能
- 🆕 新增 allowCustomOption 可开启通过搜索输入增加 option
- 🆕 新增 notFoundContent 可配置无搜索结果的展示内容
- 🆕 新增 dropdownClassName && dropdownStyle 可对 dropdown overlay 进行样式设置
- 🆕 新增 borderd 属性，可配置有无边框
- 🆕 新增 arrowComponent 属性，可配置箭头 icon 组件
- 🆕 新增 autoWidth 属性, 可配置下拉框是否自动和选择框同宽
- 🆕 新增 matchPredicate 方法，是否有绝对匹配的判断方法，影响在有绝对匹配下的行为，例如是否需要创建新的 option
- 🆕 新增 onSearch 方法，当搜索框内容变化时返回
- 🆕 新增 onSelect 方法，选中时回调
- 🆕 新增 onDeSelect 方法，取消时回调
- 🆕 新增 dropDownVisible 属性，控制是否展示 dropdown
- 🆕 新增 onDropdownVisibleChange 方法，当 dropdown visible 属性改变时回调。
- 🛎 width, width 现可用 classname 或 style 来控制。
- 🛎 siz 属性现在可以受 sizeContext 控制
- 🛎 options 现在不允许自定义格式，保持和 List option 格式一致
- 🛎 value && defaultValue 现在可接受 string 或者 string[] 分别对应单选和多选模式
- 🛎 onChange 方法的输入值 (options: …
=> docs(release): @gio-design/components 20.11.0 change log

packages/components/src/components/date-picker/__tests__/__snapshots__/data-picker.spec.js.snap, packages/components/src/components/input/Input.tsx, packages/components/src/components/input/__tests__/__snapshots__/input.test.js.snap, packages/components/src/components/input/interfaces.ts, packages/components/src/components/input/style/index.less, packages/components/src/components/pagination/Pagination.tsx, packages/components/src/components/pagination/__test__/__snapshots__/Pagination.test.js.snap, packages/components/src/components/search-bar/index.tsx, packages/components/src/components/search-bar/interfaces.ts, packages/components/src/components/select/__tests__/Select.test.js, packages/website/src/components/basic/input/index.zh-CN.md
- 输入框
- 修复组件内的className会被覆盖
---
- Input 
-  fix internal className will be cover
=> fix(input): fix internal className will be cover

packages/components/src/components/date-picker/__tests__/__snapshots__/data-picker.spec.js.snap, packages/components/src/components/date-picker/datePicker.tsx, packages/components/src/components/date-picker/style/index.less
- 日期选择器
修改全局的gio-input类名
---
- data-picker
fix global gio-input classname
=> style(date-picker): fix global className conflict

packages/components/src/components/dropdown/Dropdown.tsx, packages/components/src/components/dropdown/__test__/Dropdown.test.js
- 下拉框
- 定义交互逻辑，当未传visible参数点击overlay区域会关闭下拉框。
---
- Dropdown
- define dropdown interaction, it will be close after click the overlay area without visible.
=> fix(dropdown): define dropdown interaction

.eslintrc.js, packages/components/src/components/tab-nav/TabNav.tsx, packages/components/src/components/tabs/Tabs.tsx, packages/components/src/components/tabs/__tests__/Tabs.test.js
fix the eslint error
- 标签导航
- 修复eslint错误
- 标签页
- 修复eslint错误
---
- tab-nav
- fix the eslint error
- tabs
- fix the eslint error
=> refactor(tab-nav/tabs): fix the eslint error

packages/components/src/components/input/Input.tsx, packages/components/src/components/input/interfaces.ts, packages/website/src/components/basic/input/demo/Input.tsx, packages/website/src/components/basic/input/demo/TextArea.tsx, packages/website/src/components/basic/input/index.zh-CN.md
- Input
- 修复 rest 解构覆盖value属性的问题
- input 文档更新同步
=> fix(input): fix the problem that destructing the rest may overwrite value field，and update input document

packages/components/src/components/button/style/mixin.less
- 按钮
- 修复父节点 mouseleave 事件无法被触发 当按钮是disabled的时候。
---
- Button
- fix parent node mouseleave not work when button disabled
=> fix(button): fix parent node mouseleave not work when button disabled

packages/components/src/components/tooltip/Tooltip.tsx, packages/components/src/components/tooltip/__tests__/Tooltip.test.js
- 文字提示
- disabled 状态下不应该改变内部visible状态
---
- Tooltip
- should not update internal state when tooltip disabled
=> fix(tooltip): fix trigger disabled bug

packages/components/src/components/avatar/Avatar.tsx, packages/components/src/components/avatar/__tests__/Avatar.test.js, packages/components/src/components/avatar/__tests__/AvatarGroup.test.js, packages/components/src/components/avatar/__tests__/__snapshots__/AvatarGroup.test.js.snap, packages/components/src/components/banner/Banner.tsx, packages/components/src/components/banner/__tests__/Banner.spec.js, packages/components/src/components/banner/__tests__/__snapshots__/Banner.spec.js.snap, packages/components/src/components/checkbox/checkbox.tsx, packages/components/src/components/checkbox/group.tsx, packages/components/src/components/drawer/index.tsx, packages/components/src/components/dropdown/__test__/Dropdown.test.js, packages/components/src/components/dropdown/index.tsx, packages/components/src/components/input/Input.tsx, packages/components/src/components/input/TextArea.tsx, packages/components/src/components/input/__tests__/input.test.js, packages/components/src/components/select/__tests__/Select.test.js, packages/components/src/components/tree-select/__tests__/tree-select.test.js
fix other components stylelint and eslint error
- 警告提示
- 修复stylelint和eslint错误
- 头像
- 修复stylelint和eslint错误
- 横幅
- 修复stylelint和eslint错误
- 单选框
- 修复stylelint和eslint错误
- 抽屉
- 修复stylelint和eslint错误
- 下拉菜单
- 修复stylelint和eslint错误
- 输入框
- 修复stylelint和eslint错误
- 选择器
- 修复stylelint和eslint错误
- 树形选择器
- 修复stylelint和eslint错误
---
- alert
- fix stylelint and eslint error
- avatar
- fix stylelint and eslint error
- banner
- fix stylelint and eslint error
- checkbox
- fix stylelint and eslint error
- drawer
- fix stylelint and eslint error
- dropdown
- fix stylelint and eslint error
- input
- fix stylelint and eslint error
- select
- fix stylelint and eslint error
- tree-select
- fix stylelint and eslint error
=> style(other components): fix the stylelint and eslint error

packages/components/src/components/checkbox/interface.tsx, packages/components/src/components/checkbox/style/index.less, packages/components/src/components/table/hook/useSelection.tsx, packages/website/src/components/functional/table/demo/pagination.tsx
- 列表
- 选择点击设置停止冒泡
- 多选框
- 添加 onClick 参数, 将input hidden 变成透明，其他元素禁止事件
---
- Table
- selection onClick stopPropagation
- CheckBox
- add onclick prop, update input hidden to transparent，other domelement pointer-events: none
=> fix(table, checkbox): fix onRow-click be call when click table selection

packages/components/src/components/banner/Banner.stories.tsx, packages/components/src/components/banner/interface.ts, packages/components/src/components/date-picker/DatePicker.stories.tsx, packages/components/src/components/date-picker/interface.tsx, packages/components/src/components/date-picker/style/index.less, packages/components/src/components/dropdown/Dropdown.stories.tsx, packages/components/src/components/dropdown/interface.ts, packages/components/src/components/form/Form.stories.tsx, packages/components/src/components/form/Form.tsx, packages/components/src/components/form/Item.tsx, packages/components/src/components/form/context.tsx, packages/components/src/components/form/index.tsx, packages/components/src/components/form/interface.ts, packages/components/src/components/form/style/demo.less, packages/components/src/components/list/List.stories.tsx, packages/components/src/components/list/interface.ts, packages/components/src/components/modal/Model.stories.tsx, packages/components/src/components/modal/interface.ts, packages/components/src/components/pagination/Pagination.stories.tsx, packages/components/src/components/pagination/interface.tsx, packages/components/src/components/popconfirm/Popconfirm.stories.tsx, packages/components/src/components/popconfirm/interface.ts, packages/components/src/components/popover/Popover.stories.tsx, packages/components/src/components/popover/interface.ts, packages/components/src/components/popover/style/demo.less
add stories to some Functional components
- 横幅/日期选择器/下拉菜单/表单/列表/弹窗/分页/气泡确认框/气泡卡片
- 增加上述组件的story
---
- Banner/DatePicker/Dropdown/Form/List/Modal/Pagination/Popconfirm/Popover
- add stories to upper components
=> docs: add stories to some Functional components

packages/components/src/components/button/__tests__/__snapshots__/button.test.js.snap, packages/components/src/components/button/button.tsx, packages/components/src/components/button/style/index.less, packages/components/src/components/dropdown/__test__/__snapshots__/Dropdown.test.js.snap, packages/components/src/components/upload/__tests__/__snapshots__/upload.test.js.snap
define background to concrete className
- 按钮
- 将background定义到具体的className上，给button一个默认的type
---
- button
- Define background to the specific classname and give button a default type
=> style(button): define background to concrete className

packages/components/src/components/input/style/index.less, packages/components/src/components/search-bar/__tests__/__snapshots__/searchbar.test.js.snap, packages/components/src/components/search-bar/index.tsx, packages/components/src/components/search-bar/interfaces.ts, packages/components/src/components/search-bar/style/index.less, packages/website/src/components/functional/searchBar/demo/index.tsx, packages/website/src/components/functional/searchBar/index.zh-CN.md
resolve some problems in search-bar
- 搜索框
- 解决searchBar中图标垂直不居中的问题
- 给searchBar组件的demo里加上placeholder
- 处理searchBar中icon和边框间距的问题
- 让id，value，onChange设置为可选
- 搜索列表为空时，searchBar的focus不应该显示下拉框
- 解决搜索框搜索列表显示逻辑错误的问题
- 支持esc键退出列表
- 差异化显示输入信息和建议信息之间的差异
- 搜索列表中数据少于设定的条数时，让下拉列表的高度自适应
---
- SearchBar
- Solve the problem that the text Icon in searchBar is not centered vertically
- Add a placeholder to the demo of the searchBar component
- Dealing with the problem of icon and border spacing in searchBar
- Set ID, value, onchange to optional
- When the search list is empty, the search bar's focus should not display a drop-down box
- Solve the problem of logic error in search box search list display
- Support ESC key exit list
- Differentiation shows the …
=> fix(search-bar): resolve some problems in search-bar

packages/components/src/components/cascader/index.tsx, packages/components/src/components/checkbox/index.tsx, packages/components/src/components/grid/index.tsx, packages/components/src/components/input/index.tsx, packages/components/src/components/link/index.tsx, packages/components/src/components/link/interface.ts, packages/components/src/components/list/index.ts, packages/components/src/components/menu/index.tsx, packages/components/src/components/modal/Model.stories.tsx, packages/components/src/components/modal/index.tsx, packages/components/src/components/popover/index.tsx, packages/components/src/components/progress/index.tsx, packages/components/src/components/radio/index.tsx, packages/components/src/components/search-bar/index.tsx, packages/components/src/components/select/index.tsx, packages/components/src/components/sign/index.ts, packages/components/src/components/tabs/index.tsx, packages/components/src/components/tag/index.tsx, packages/components/src/components/time-picker/index.tsx, packages/components/src/components/toast/index.tsx, packages/components/src/components/toggles/index.tsx, packages/components/src/components/upload/index.tsx, packages/components/src/index.ts
- 完善 components 根目录导出的 props 及其他相关类型
- 完善带有多个子组件的组件写法，对 babel-import-plugin 支持的动态加载更友好
=> refactor(components): add props exports for all components

.huskyrc.js, packages/components/src/components/loading/Loading.tsx, packages/components/src/components/loading/interface.ts, packages/components/src/components/loading/style/index.less, packages/components/src/components/table/Table.tsx, packages/components/src/components/table/Title.tsx, packages/components/src/components/table/__test__/Table.test.js, packages/components/src/components/table/hook/usePagination.tsx, packages/components/src/components/table/interface.ts, packages/components/src/components/table/style/index.less, packages/website/src/components/functional/table/demo/loading.tsx, packages/website/src/components/functional/table/index.zh-CN.md
ISSUES CLOSED: #570 #539
- 列表
- 修复 onChange 回调不能拿到最新的分页状态
- 添加加载功能
---
- Table
- fix onChange can't get latest pagination state
- add loading feature
=> fix(table): fix onChange can't get latest pagination state

packages/components/src/components/list/list.tsx, packages/components/src/components/list/style/option.less, packages/website/src/components/functional/list/demo/avatar.tsx
=> fix(list): fix list item spacing

packages/components/src/components/list/interface.ts, packages/components/src/components/list/list.tsx, packages/components/src/components/select/Select.tsx, packages/website/src/components/functional/select/demos/options.ts
=> fix(select): fix select group listHeight

packages/components/src/components/tab-nav/TabNav.tsx, packages/components/src/components/tab-nav/__test__/TabNav.test.js, packages/components/src/components/tab-nav/interface.ts, packages/components/src/components/tabs/Tabs.tsx, packages/components/src/components/tabs/__tests__/Tabs.test.js, packages/components/src/components/tabs/interface.ts, packages/components/src/utils/hooks/useDeepCompareMemo.ts, packages/website/src/components/basic/tabnav/index.zh-CN.md, packages/website/src/components/basic/tabs/demo/block.tsx, packages/website/src/components/basic/tabs/index.zh-CN.md
- 标签导航，标签页
- 重构标签导航和标签页
- 去掉key的number 类型
---
-  tabs, tab-nav
- refactor tabs and tab-nav
- remove number type in key
=> refactor(tabs, tab-nav): refactor tabs and tab-nav

packages/components/src/components/date-picker/dateRangePicker.tsx, packages/components/src/components/date-picker/style/index.less, packages/components/src/components/input/style/index.less, packages/components/src/index.ts
change input disabled color and restore dateRangePicker's change
- 输入框
- 修改input输入框disabled时的颜色
- 日期选择器
- dateRangePicker的失焦隐藏实现存在问题，先去掉
- 将datePicker及dateRangePicker从index里导出
---
- input
- change input disabled color 
- datePicker
- There is a problem with the defocus hiding implementation of daterangepicker, which is removed temporarily
- export datePicker and dateRangePicker from index
=> style(input/date_picker): change input disabled color

packages/components/src/components/date-picker/DatePicker.stories.tsx, packages/components/src/components/date-picker/__tests__/date-picker.spec.js, packages/components/src/components/date-picker/datePicker.tsx, packages/components/src/components/date-picker/dateRangePicker.tsx, packages/components/src/components/date-picker/interface.tsx, packages/website/src/components/functional/date-picker/demo/base.tsx, packages/website/src/components/functional/date-picker/demo/range.tsx, packages/website/src/components/functional/date-picker/index.zh-CN.md
add onblur to dateRangePicker and remove onSelect from props
- 日期选择器
- 给dateRangePicker设置失焦隐藏
- 将onSelect从参数列表里删除
- 修复dateRangePicker点击取消或者失焦时行为和点击确定按钮一样的问题
---
- datePicker
- Defocus setting for picker Ranger
- Delete onSelect from props
- Fixed the same behavior of daterangepicker when clicking cancel or defocus as when clicking OK
=> fix(date-picker): add onblur and remove onSelect from props

packages/components/src/components/sign/Number.tsx, packages/components/src/components/sign/Sign.tsx, packages/components/src/components/sign/__tests__/__snapshots__/sign.test.js.snap, packages/components/src/components/sign/interface.ts, packages/components/src/components/sign/style/index.less, packages/website/src/components/basic/sign/demos/sign.tsx, packages/website/src/components/basic/sign/index.zh-CN.md
- 标记
- 添加offset参数
---
- Component 1
- add offset prop
=> feat(sign): add offset prop

packages/components/src/components/avatar/Avatar.tsx, packages/components/src/components/avatar/__tests__/__snapshots__/Avatar.test.js.snap, packages/components/src/components/avatar/__tests__/__snapshots__/AvatarGroup.test.js.snap, packages/components/src/components/avatar/style/index.less
- 头像
- 修复 #617 造成的样式错误
---
- Avatar
-  fix style error caused by #617
=> fix(avatar): fix style error caused by #617

packages/components/src/components/radio/Radio.tsx
fix the radio style when radio-group is disabled
- 单选框
- 修复当radioGroup设置为disabled时，里面的radio仍可以触发hover动作，主要原因是Radio没有接收到RadioGroup传来的disabled属性，导致gio-radio__wrapper--disabled样式没有生效。
---
- Radio
- Fix that when the radio group is set to disabled, the radio in it can still trigger the hover action. The main reason is that the radio does not receive the disabled attribute from the radio group, resulting in the gio-radio__ Wrapper--disabled style does not work.
=> style(radio): fix the radio style when radio-group is disabled

packages/components/src/components/checkbox/style/index.less
fix the checkbox cursor when disabled
- 多选框
- 修复checkbox在disabled状态时cursor仍为pointer的问题
---
- checkbox
- Fix the problem that the cursor is still a pointer when the checkbox is in the disabled state
=> fix(checkbox): fix the checkbox cursor when disabled

packages/components/src/components/select/Select.tsx, packages/website/src/components/functional/select/demos/single.tsx
not set ref, the width will not take effect
当不设置ref时，设置width失效
ISSUES CLOSED: #647
- Component 
- select
=> fix(select): invalid custom width

packages/components/src/components/modal/CalloutModal.tsx
fix the modal click onOk don't close in CalloutModal
- 弹窗
- 修复modal组件在函数式调用时点击确定按钮modal没有关闭的问题
---
- Modal
- Fix the problem that the modal component does not close when it clicks the OK button in the functional call
=> fix(modal): fix the modal click onOk don't close in CalloutModal

src/components/toggles/Toggles.mdx, src/components/toggles/Toggles.stories.tsx
add stories and document for toggles component
=> docs(toggles): add stories and document for toggles component

src/components/select/OptionsList/OptionItem.tsx, src/components/select/Select.stories.tsx, src/components/select/__tests__/Select.test.js
=> test(select): add select test

src/components/time-picker/__tests__/Combobox.test.js, src/components/time-picker/__tests__/__snapshots__/Combobox.test.js.snap, src/components/tree-select/TreeSelect.tsx
tree-select组件引入了slide动画，但是不知道什么时候，slide动画的样式被删除了还是咋滴，反正就出问题了。所以tree-select组件也就不引入slide动画了
=> fix(tree-select): 解决slide动画引发的bug

src/components/cascader/helper.ts
=> fix(cascader): getParentByValue

src/components/col/index.ts, src/components/col/style/index.less, src/components/col/style/index.ts, src/components/grid/Grid.stories.tsx, src/components/grid/style/index.ts, src/components/menu/index.ts, src/components/modal/index.tsx, src/components/row/index.ts, src/components/row/style/index.less, src/components/row/style/index.ts, src/index.ts
good 
import { Tab } from '@gio-design/component'
then use Tab and Tab.Pane 
bad 
import { Tab, TabPane } from '@gio-design/component'
bad
import Tab from  '@gio-design/component/es/compoents/tab';
close #901
=> feat: support babel-plugin-import

src/components/select/Select.stories.tsx, src/components/select/Selector/index.tsx, src/components/select/__tests__/__snapshots__/Select.test.js.snap, src/components/select/style/index.less
=> fix(select): text ellipsis  error

src/components/select/Select.stories.tsx, src/components/select/Select.tsx, src/components/select/Selector/index.tsx, src/components/select/interface.ts
fix(select): fix select props classname error
feat: triggerComponent 新增自定义 trigger参数
这个pr暂时先不合并
=> fix(select): fix select props classname error

src/list-picker/demos/List-picker.stories.tsx, src/list-picker/interfance.ts, src/list-picker/listPicker.tsx, src/list/List.tsx, src/list/Selection.tsx, src/list/context.tsx, src/list/hooks/useCacheOptions.ts, src/list/inner/CascaderItem.tsx, src/list/interfance.ts
1. 新增selection consumer  渲染 children的方式，为了支持全部这种操作
2. listPicker 单选模式下脱离非受控模式，当为单选模式时，遵循完全受控模式
3. listPicker 提升disabled层级，trigger的disabled交给listPicker来控制
=> fix(list-picker): selection consumer render children

src/cascader/Cascader.tsx, src/cascader/Trigger.tsx, src/cascader/demos/Cascader.stories.tsx, src/cascader/interfance.ts, src/dropdown/Dropdown.tsx, src/input/Input.tsx, src/input/demos/Input.stories.tsx, src/input/interface.ts, src/legacy/filter-picker/components/FilterList/Expression/FilterCondition/FilterAttrOverlay.tsx, src/list-picker/Trigger.tsx, src/list-picker/demos/List-picker.stories.tsx, src/list-picker/interfance.ts, src/list-picker/listPicker.tsx, src/list-picker/style/index.less, src/list/List.tsx, src/list/demos/List.stories.tsx, src/list/interfance.ts, src/pagination/RowsSelector.tsx, src/popover/Popover.tsx, src/popover/style/index.less, src/select/Select.tsx, src/select/Trigger.tsx, src/select/demos/Select.stories.tsx, src/select/interface.ts
1. listPicker
2. select
3. casacder
整理了以上这些 组件 有关 trigger的样式控制，让控制起来的难度更小一些
- 移除 triggerProps 参数 将 style, className, allowClear, prefix, suffix, hidePrefix,title,placeholder拿出，需要各位配合着改一下有关这里样式的问题。
- inputButton 统一包装一层div, 可在组件内部使用 style、className样式来覆盖
- 综合考虑 将 inputButton 的ref修正在 新包装的div上，用来解决popover根据ref定位时，偏移问题
各类trigger样式控制:
跟随父级宽度 style={{width:'100%'}} 
自动宽(不需要设定宽度)
自定义宽度 style={{width:'240px'}}
二：
1. select 新增 allowWith 自动设置 content宽度 与 原有select保持一致
2. 修复 tooltip allow 小三角指向问题
3. list新增 onClick 方法
4. Input 组件重新定义ref指向
=> fix(style): clear up all trigger style controls

src/cascader/Cascader.tsx, src/cascader/demos/Cascader.stories.tsx, src/list-picker/Recent.tsx, src/list-picker/demos/List-picker.stories.tsx, src/list-picker/style/index.less, src/list/DragItem.tsx, src/list/Item.tsx, src/list/List.tsx, src/list/Selection.tsx, src/list/context.tsx, src/list/demos/List.stories.tsx, src/list/inner/CascaderItem.tsx, src/list/inner/CheckboxItem.tsx, src/list/inner/baseItem.tsx, src/list/interfance.ts, src/list/style/index.less, src/list/util.ts, src/select/Select.tsx
本次更新将 Item的wrapper设为 废弃，在未来可能会完全丢弃掉该方法：
目前新增了如下替代wrapper的方式：
```jsx
<Popover content={()=> {
/** some code ...... */
}}>
<List.Item value='free'>支持</List.Item>
</Popover>
```
当然，本次升级后，理论上可以用ListContext 来模拟 Item 的行为，您完全可以自主的创建一个全新的Item 并且还可以接入到 List、Cascader、list-picker 、 select 等等当中
=> fix(list-picker): 优化list-picker、cascader性能

src/popover/Popover.tsx
当content被关闭时，无法触发onMouseLeave 导致 父子组件visible不一致
具体表现为 popover只可打开一次后再无法打开
=> fix(popover): visible error

src/modal/Modal.tsx
将footer参数从restProps中拿出来，避免最后结构restProps时覆盖自定义footer
=> fix(footer):fix default footer

src/button/style/index.less, src/list/inner/baseItem.tsx
1. 修复button disabled时 onMouseLeave 触发机制问题 浏览器原生button disabled时，会导致无法触发鼠标事件，比如:onMouseLeave/Enter/Out 等等，外层包裹了div后可以触发onMouseEnter事件了，但是还无法触发Leave，是因为鼠标事件的target为 button时，导致无法触发。
2. 修复select 组件 disabledTooltip 宽度问题  https://www.zhangxinxu.com/wordpress/2015/05/css3-transform-affect/ 问题背景为transform会影响position:absoulte/fixed 的一些属性 比如：宽度，相对定位等
=> fix(button): mouseLeave trigger error

src/panel/style/index.less
=> fix(panel): the title should be vertically centered with the icon when there is no description

src/cascader/Cascader.tsx, src/cascader/interfance.ts, src/list-picker/Trigger.tsx, src/list-picker/interfance.ts, src/list-picker/listPicker.tsx, src/list/context.tsx, src/list/hooks/useCacheOptions.ts, src/list/index.tsx
优化label解析方式，当model=== 'cascader'且value中值包含'.'时，需要变更修改valueSeparator参数
such as "www.baidu.com",会导致解析失败
=> fix(list): fix list value separator

src/popover/Popover.tsx, src/popover/interface.ts
Warning: React does not recognize the `arrowPointAtCenter` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `arrowpointatcenter` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
=> fix(popover): fix react wraning

src/link/style/index.less
减少了 hover 时的选择器优先级，同时去掉 hover 时调用 .reset()
=> fix(link): reduce selector's specificity

src/static-date-picker/DatePicker.tsx, src/static-date-picker/interfaces.ts, src/static-date-picker/style/index.less, src/static-past-time-picker/RelativeRangeBody.tsx
1. 解决了 #1863 引入的 `disabledDate` 判断错误，导致将月份和年份也错误 disabled 的问题；
2. 解决了过去动态时段-回显数据时，时间选择器面板未定位到已选定日期的问题；
=> fix(static-date-picker): fix some bug

src/legacy/filter-picker/components/FilterList/Expression/FilterCondition/attrSelect.less, src/legacy/filter-picker/components/FilterList/Expression/FilterCondition/index.tsx, src/legacy/filter-picker/components/FilterList/Expression/index.less
`filter-condition` 的样式包在了 `.expression-box` 选择器中，如果单独使用 `filter-condition` 组件，会导致样式失效，所以需要单独拎出来。
=> fix(filter-picker): fix style of FilterCondition

src/past-time-picker/PastTimePicker.tsx, src/past-time-picker/demos/PastTimePicker.stories.tsx, src/past-time-picker/interfaces.ts, src/static-past-time-picker/SinceRangePicker.tsx, src/static-past-time-picker/StaticPastTimePicker.tsx, src/static-past-time-picker/interfaces.ts, src/static-past-time-picker/locales/en-US.ts, src/static-past-time-picker/locales/zh-CN.ts
=> feat(since-range-picker): rangePicker added earliestInHistoryRadio params controller

src/past-time-picker/PastTimePicker.tsx, src/past-time-picker/__tests__/index.test.tsx, src/past-time-picker/demos/PastTimePicker.stories.tsx, src/past-time-picker/interfaces.ts, src/static-past-time-picker/StaticPastTimePicker.tsx, src/static-past-time-picker/__tests__/AbsoluteRangePicker.test.tsx, src/static-past-time-picker/__tests__/Index.test.tsx, src/static-past-time-picker/interfaces.ts, src/static-past-time-picker/style/QuickPicker.less, src/static-past-time-picker/utils.ts
可使用 quickOptions 替换常用选项
```
<PastTimePicker
quickOptions={[
{ value: 'day:1,0', label: '今天内' },
{ value: 'day:2,0', label: '1天前至今' },
{ value: 'day:3,0', label: '2天前至今' },
{ value: 'day:4,0', label: '3天前至今' },
{ value: 'day:5,0', label: '4天前至今' },
{ value: 'day:6,0', label: '5天前至今' },
{ value: 'day:7,0', label: '6天前至今' },
{ value: 'day:8,0', label: '7天前至今' },
{ value: 'earliest', label: '历史至今' },
]}
onSelect={console.log}
placeholder="时间范围"
disabledDate={disabledDate}
modes={[TimeMode.Since]}
/>
```
=> feat(time-picker): 添加自定义quick option
