growingio/gio-design

- packages/components/package.json
> chore(components): upgrade gio-rewire

- .github/workflows/ci.yml
- .huskyrc.js
- packages/website/src/components/basic/breadcrumb/index.zh-CN.md
Replace 'yarn build' with 'yarn test' for git pre-push hook.
> chore: update ci workflow

- packages/components/.gio-rewire.js
- packages/components/package.json
- yarn.lock
upgrade gio rewire to 1.0.4 to fix watch mode break in some unknow case
> chore(packages/components): upgrade gio-rewire

- packages/components/src/components/link/__tests__/__snapshots__/link.test.js.snap
- packages/components/src/components/link/__tests__/link.test.js
- packages/components/src/components/link/index.tsx
- packages/components/src/components/link/interface.ts
- packages/components/src/components/link/style/index.less
- packages/components/src/components/link/style/index.ts
- packages/components/src/index.ts
- packages/components/src/typings/OverridableComponent.d.ts
- packages/website/src/components/basic/breadcrumb/index.zh-CN.md
- packages/website/src/components/basic/checkbox/index.zh-CN.md
- packages/website/src/components/basic/link/demos/customLink.tsx
- packages/website/src/components/basic/link/demos/link.tsx
- packages/website/src/components/basic/link/index.zh-CN.md
- packages/website/src/components/basic/radio/index.zh-CN.md
- packages/website/src/components/basic/toast/index.zh-CN.md
- yarn.lock
> feat(component,website): add component Link

- packages/website/src/develop/changelog/components.zh-CN.md
> docs(website): components 20.6.2 changelog

- .github/workflows/auto_rebase.yml
详情见：https://github.com/cirrus-actions/rebase
> chore: add auto rebase action

- packages/components/src/components/checkbox/__tests__/__snapshots__/checkbox.test.js.snap
- packages/components/src/components/checkbox/__tests__/__snapshots__/group.test.js.snap
- packages/components/src/components/checkbox/checkbox.tsx
- packages/components/src/components/checkbox/style/index.less
- packages/website/src/components/basic/checkbox/demo/basic.tsx
- packages/website/src/components/basic/checkbox/demo/partial.tsx
> style(checkbox check icon style): using Fillet check icon

- packages/website/src/develop/changelog.zh-CN.md
- packages/website/src/develop/changelog/components.zh-CN.md
- packages/website/src/develop/changelog/tokens.zh-CN.md
- packages/website/src/resources/tokens.zh-CN.md
> docs(website): components and tokens 20.7.0 changelog

- packages/website/src/develop/changelog.zh-CN.md
- packages/website/src/develop/changelog/icons.zh-CN.md
> docs: icons 20.7.0 changelog

- packages/components/src/components/avatar/__tests__/Avatar.test.js
- packages/components/src/components/avatar/__tests__/AvatarGroup.test.js
- packages/components/src/components/popover/__tests__/Popover.test.js
- packages/components/src/components/tooltip/__tests__/Tooltip.test.js
use done() function delay test exit.
> test(test): add missing catch async test result

- packages/components/package.json
- packages/playground/package.json
- packages/themes/package.json
- packages/tokens/package.json
- packages/website/package.json
- packages/website/src/develop/changelog/components.zh-CN.md
- packages/website/src/develop/changelog/tokens.zh-CN.md
> chore: components and tokens 20.8.0 changelog

- packages/components/src/components/tabs/TabPane.tsx
- packages/components/src/components/tabs/Tabs.tsx
- packages/components/src/components/tabs/index.tsx
- packages/components/src/components/tabs/interface.ts
- packages/components/src/components/tabs/style/index.less
- packages/tokens/properties/color/background.json
- packages/tokens/properties/color/text.json
- packages/tokens/properties/shadow.json
- packages/website/src/components/basic/tabs/demo/icon.tsx
- packages/website/src/components/basic/tabs/index.zh-CN.md
> refactor(tabs): tabs remove icon dependence

- packages/components/src/components/avatar/Avatar.tsx
- packages/components/src/components/avatar/style/index.less
- packages/icons/src/More.tsx
- packages/icons/src/index.tsx
- packages/icons/svgs/more.svg
affects: @gio-design/components, @gio-design/icons
ISSUES CLOSED: #42
> refactor(avatar): use @gio-design/icons in avatar

- packages/components/src/components/avatar/AvatarGroup.tsx
- packages/components/src/components/avatar/__tests__/AvatarGroup.test.js
- packages/components/src/components/avatar/__tests__/__snapshots__/AvatarGroup.test.js.snap
> fix(avatar): update text "n+" with "+n" in the AvatarGroup last item

- packages/components/src/components/tabs/style/index.less
- packages/website/src/components/basic/tabs/demo/blockSize.tsx
- packages/website/src/components/basic/tabs/demo/icon.tsx
- packages/website/src/components/basic/tabs/demo/lineSize.tsx
> style(tabs): fix style omit

- packages/components/src/components/sign/Dot.tsx
- packages/components/src/components/sign/Number.tsx
- packages/components/src/components/sign/__tests__/__snapshots__/sign.test.js.snap
- packages/components/src/components/sign/__tests__/sign.test.js
- packages/components/src/components/sign/index.tsx
- packages/components/src/components/sign/interface.ts
- packages/components/src/components/sign/style/index.less
- packages/components/src/components/sign/style/index.ts
- packages/components/src/components/sign/style/mixin.less
- packages/tokens/properties/color/background.json
- packages/website/src/components/basic/sign/demos/demo.less
- packages/website/src/components/basic/sign/demos/dot.tsx
- packages/website/src/components/basic/sign/demos/dotSize.tsx
- packages/website/src/components/basic/sign/demos/placement.tsx
- packages/website/src/components/basic/sign/demos/showZero.tsx
- packages/website/src/components/basic/sign/demos/sign.tsx
- packages/website/src/components/basic/sign/index.zh-CN.md
> feat(components): add sign component

- packages/components/package.json
- packages/icons/package.json
- packages/playground/package.json
- packages/themes/package.json
- packages/tokens/package.json
- packages/website/.umirc.ts
- packages/website/package.json
- packages/website/src/develop/changelog.zh-CN.md
- packages/website/src/develop/changelog/components.zh-CN.md
- packages/website/src/develop/changelog/icons.zh-CN.md
- packages/website/src/develop/changelog/tokens.zh-CN.md
- yarn.lock
affects: @gio-design/components, @gio-design/icons, playground, @gio-design/themes,
@gio-design/tokens, website
> docs(website): components & tokens 20.8.1 and icons 20.8.0 changelog

- packages/website/src/components/basic/tag/demos/basic.tsx
- packages/website/src/components/basic/tag/demos/closable.tsx
- packages/website/src/components/basic/tag/demos/hoverClose.tsx
- packages/website/src/components/basic/tag/demos/index.less
- packages/website/src/components/basic/tag/demos/prorupt.tsx
- packages/website/src/components/basic/tag/demos/version.tsx
> fix(website): change class name that affect global

- .github/workflows/cd.yml
- package.json
- packages/website/.umirc.gh-pages.ts
- packages/website/.umirc.production.ts
- packages/website/.umirc.ts
- packages/website/package.json
- yarn.lock
Remove unused files and packages.
> chore(website): update umi configuration

- packages/components/package.json
- packages/icons/package.json
- packages/themes/package.json
- packages/tokens/package.json
- packages/website/package.json
- packages/website/src/develop/changelog.zh-CN.md
- packages/website/src/develop/changelog/components.zh-CN.md
- packages/website/src/develop/changelog/icons.zh-CN.md
- packages/website/src/develop/changelog/tokens.zh-CN.md
affects: @gio-design/components, @gio-design/icons, @gio-design/themes, @gio-design/tokens, website
> docs(website): components & tokens 20.8.2 and icons 20.8.1 changelog

- packages/components/src/components/button/style/index.less
- packages/components/src/components/button/style/mixin.less
- packages/website/src/components/basic/loading/index.zh-CN.md
> docs(loading): show subtitle "参数说明" in loading doc

- packages/components/src/components/progress/Progress.tsx
- packages/components/src/components/progress/__tests__/Progress.test.js
- packages/components/src/components/progress/__tests__/__snapshots__/Progress.test.js.snap
- packages/components/src/components/progress/index.tsx
- packages/components/src/components/progress/interface.ts
- packages/components/src/components/progress/style/index.less
- packages/components/src/index.ts
- packages/website/src/components/basic/progress/demos/index.tsx
- packages/website/src/components/basic/progress/index.zh-CN.md
> feat(components): progress

- packages/components/src/components/popconfirm/style/index.less
- packages/tokens/properties/color/text.json
> style(popconfirm, loading, tabs): update tokens

- commitlint.config.js
- lint-staged.config.js
- packages/components/src/components/breadcrumb/index.tsx
- packages/components/src/components/breadcrumb/style/index.less
- packages/components/src/components/breadcrumb/style/index.ts
- packages/tokens/properties/color/text.json
- packages/website/src/components/basic/breadcrumb/demo/basic.tsx
> style(breadcrumb): use design tokens in breadcrumb

- packages/components/src/components/button/style/index.less
- packages/components/src/components/button/style/mixin.less
- packages/tokens/properties/color/background.json
- packages/tokens/properties/color/border.json
- packages/tokens/properties/color/text.json
- packages/tokens/properties/palette.json
- packages/website/src/components/basic/button/demos/icon.tsx
- packages/website/src/components/basic/button/demos/index.less
- packages/website/src/components/basic/button/demos/primary.tsx
- packages/website/src/components/basic/button/demos/secondary.tsx
- packages/website/src/components/basic/button/index.zh-CN.md
> feat(button): add icon button and update tokens

- packages/components/src/components/tree/style/index.less
- packages/tokens/properties/color/text.json
> style(tokens): remove unused token for tree

- packages/components/src/components/drawer/style/drawer.less
- packages/components/src/components/input/style/index.less
- packages/components/src/components/sign/style/index.less
> style: use new name for dark tokens in components

- lerna.json
- package.json
- packages/components/package.json
- packages/icons/package.json
- packages/tokens/package.json
- packages/website/package.json
- packages/website/src/develop/changelog/components.zh-CN.md
- packages/website/src/develop/changelog/icons.zh-CN.md
- packages/website/src/develop/changelog/tokens.zh-CN.md
- yarn.lock
> chore(website): gio-design@20.8.3 changelog

- packages/components/package.json
- packages/website/src/develop/changelog/components.zh-CN.md
> chore(website): @gio-design/components@20.8.4 changelog

- packages/components/src/components/pagination/Pagination.tsx
- packages/components/src/components/pagination/__test__/__snapshots__/Pagination.test.js.snap
- packages/components/src/components/pagination/style/index.less
> style(pagination): change icon size, hidden option if not set

- .github/dependabot.yml
- .github/workflows/cd.yml
- .github/workflows/ci.yml
- CNAME
- azure-pipelines.yml
更新了 CD 流程：
- 增加了判断：当提交的 commit message 不是 `feat`、`fix` 或 `docs` 三种类型就不会更新 GrowingIO Design 网站。
- 将网站部署到 [Surge](https://surge.sh)，停止使用 Netlify。
> chore: update github actions workflows

- packages/components/src/components/button/button.tsx
- packages/components/src/components/button/interface.tsx
- packages/website/src/components/basic/button/index.zh-CN.md
> feat(components，website): 给button添加tooltip

- packages/components/src/components/button/button.tsx
- packages/components/src/components/button/interface.tsx
- packages/website/src/components/basic/button/index.zh-CN.md
Reverts growingio/gio-design#127
> revert: feat(components，website): 给button添加tooltip

- packages/components/src/components/avatar/style/index.less
> style(avatar): set user-select:none, use object-fit on img

- packages/components/src/components/pagination/Pagination.tsx
- packages/components/src/components/pagination/__test__/Pagination.test.js
- packages/components/src/components/pagination/interface.tsx
- packages/website/src/components/functional/pagination/index.zh-CN.md
> feat(pagination): add hideOnSinglePage prop

- packages/components/src/components/loading/Loading.tsx
- packages/components/src/components/loading/interface.ts
- packages/components/src/components/loading/style/index.less
- packages/website/src/components/basic/loading/demos/index.less
- packages/website/src/components/basic/loading/index.zh-CN.md
> refactor(loading): delete rotate prop

- packages/components/src/components/menu/style/index.less
> refactor(components): fix menu vertical align

- packages/components/package.json
- packages/components/src/components/modal/Footer.tsx
- packages/components/src/components/modal/Modal.tsx
- packages/components/src/components/modal/ModalContext.ts
- packages/components/src/components/modal/StepModal.tsx
- packages/components/src/components/modal/Title.tsx
- packages/components/src/components/modal/index.tsx
- packages/components/src/components/modal/interface.ts
- packages/components/src/components/modal/style/index.less
- packages/components/src/components/modal/style/index.ts
- packages/components/src/components/modal/style/mask.less
- packages/components/src/components/modal/style/mixin.less
- packages/components/src/components/modal/style/modal.less
- packages/components/src/index.ts
- packages/components/src/stylesheet/mixin/animation.less
- packages/website/src/components/functional/modal/demo/additionalFooter.tsx
- packages/website/src/components/functional/modal/demo/asyncConfirm.tsx
- packages/website/src/components/functional/modal/demo/maskClose.tsx
- packages/website/src/components/functional/modal/demo/modal.tsx
- packages/website/src/components/functional/modal/demo/size.tsx
- packages/website/src/components/functional/modal/demo/stepModal.tsx
- packages/website/src/components/functional/modal/index.zh-CN.md
- yarn.lock
> feat(components): add modal dialog component

- packages/components/src/components/link/index.tsx
> refactor(link): clarify type of event in link onClick

- packages/components/src/components/breadcrumb/Breadcrumb.tsx
- packages/components/src/components/breadcrumb/BreadcrumbItem.tsx
- packages/components/src/components/breadcrumb/BreadcrumbSeparator.tsx
- packages/components/src/components/breadcrumb/__tests__/Breadcrumb.test.js
- packages/components/src/components/breadcrumb/__tests__/__snapshots__/Breadcrumb.test.js.snap
- packages/components/src/components/breadcrumb/index.tsx
- packages/components/src/components/breadcrumb/interface.tsx
- packages/components/src/components/button/button.tsx
- packages/components/src/utils/reactNode.ts
> test(breadcrumb): add Breadcrumb test

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/package.yml
- CNAME
- packages/website/public/CNAME
add custom domain for gh-pages branch.
> chore: update ci/cd/package workflows

- packages/components/src/components/loading/Loading.tsx
- packages/components/src/components/loading/__test__/Loading.test.js
- packages/components/src/components/loading/__test__/__snapshots__/Loading.test.js.snap
- packages/components/src/components/loading/interface.ts
- packages/components/src/components/loading/style/index.less
- packages/tokens/properties/color/background.json
- packages/website/src/components/basic/loading/demos/blurColor.tsx
- packages/website/src/components/basic/loading/index.zh-CN.md
> feat(loading): add blurColor prop

- packages/components/src/components/avatar/Avatar.tsx
- packages/components/src/components/avatar/__tests__/__snapshots__/Avatar.test.js.snap
- packages/components/src/components/avatar/__tests__/__snapshots__/AvatarGroup.test.js.snap
- packages/components/src/components/avatar/style/index.less
- packages/components/src/components/pagination/style/index.less
- packages/components/src/components/table/style/index.less
> style(avatar,pagination,table): fix refactor icon effect

- packages/website/src/resources/iconDemos/assets/filled.svg
- packages/website/src/resources/iconDemos/assets/outlined.svg
- packages/website/src/resources/iconDemos/index.less
- packages/website/src/resources/iconDemos/index.tsx
- packages/website/src/resources/iconDemos/svgs.tsx
- packages/website/src/resources/icons.en-US.md
- packages/website/src/resources/icons.zh-CN.md
> docs: update icon component's documentation

- packages/components/src/components/alert/style/index.less
- packages/components/src/components/banner/style/index.less
- packages/components/src/components/tag/style/index.less
- packages/components/src/components/toggles/style/index.less
- packages/tokens/properties/font.json
- packages/tokens/properties/size/font.json
ISSUES CLOSED: #166
| 🇺🇸 English | update some tokens related with font |
| 🇨🇳 Chinese | 更新字体相关的 tokens |
> fix(token): update some tokens related with font

- packages/components/src/components/drawer/style/customize.less
- packages/components/src/components/drawer/style/index.less
- packages/components/src/components/popover/style/index.less
- packages/components/src/components/progress/style/index.less
- packages/components/src/components/skeleton/style/index.less
- packages/components/src/components/tooltip/style/index.less
- packages/components/src/stylesheet/mixin/trigger.less
修复 stylelint 检查出的问题，后面 CI 流程里会加上 stylelint。
> style: fix some stylelint problems

- packages/components/src/components/modal/Modal.tsx
- packages/components/src/components/modal/StepModal.tsx
- packages/website/src/components/functional/modal/demo/maskClose.tsx
- packages/website/src/components/functional/modal/index.zh-CN.md
fix step bug when close StepModal
hide footer when footer is set as false,null or undefined
fix close bug in StepModal
> fix(components): fix bug in Modal

- packages/components/package.json
- packages/icons/package.json
- packages/tokens/package.json
- packages/website/src/develop/changelog/components.zh-CN.md
- packages/website/src/develop/changelog/icons.en-US.md
- packages/website/src/develop/changelog/icons.zh-CN.md
- packages/website/src/develop/changelog/tokens.zh-CN.md
affects: @gio-design/components, @gio-design/icons, @gio-design/tokens, website
> docs: @gio-design/components 20.9.0 changelog

- packages/components/src/components/radio/Group.tsx
- packages/components/src/utils/hooks/usePrevious.ts
- packages/website/src/components/basic/radio/demos/radioGroup.tsx
https://github.com/growingio/gio-design/issues/160
| 🇺🇸 English |     fix RadioGroup onChange trigger bug; delete the import of react-use in RadioGroup    |
| 🇨🇳 Chinese |     修复 RadioGroup onChange 触发相应问题；删除 RadioGroup  对 react-use依赖      |
> fix(components): fix RadioGroup onChange trigger bug

- .eslintrc.js
- packages/components/src/components/breadcrumb/Breadcrumb.tsx
- packages/components/src/components/breadcrumb/BreadcrumbItem.tsx
- packages/components/src/components/breadcrumb/BreadcrumbSeparator.tsx
- packages/components/src/components/breadcrumb/__tests__/Breadcrumb.test.js
- packages/components/src/components/breadcrumb/__tests__/__snapshots__/Breadcrumb.test.js.snap
- packages/components/src/components/breadcrumb/interface.tsx
- packages/website/src/components/basic/breadcrumb/demo/basic.tsx
> style(breadcrumb): fix eslint errors

- packages/components/src/components/list/core.tsx
- packages/components/src/components/list/list.tsx
- packages/components/src/components/list/option.tsx
- packages/website/src/components/functional/list/demo/base.tsx
onChange return option instead of value  and fire twice on checkbox click
> fix(list): onChange return option instead of value 

- packages/components/src/components/list/interface.ts
- packages/components/src/components/list/list.tsx
- packages/components/src/components/list/normal.tsx
- packages/components/src/components/list/option.tsx
- packages/website/src/components/functional/list/demo/base.tsx
- packages/website/src/components/functional/list/demo/group.tsx
- packages/website/src/components/functional/list/index.zh-CN.md
> fix(list): add onSelect and onDeselect

- packages/components/package.json
- packages/components/src/components/button/button.tsx
- packages/components/src/components/tree-select/TreeSelect.tsx
- packages/components/src/components/tree-select/index.tsx
- packages/components/src/components/tree-select/interface.tsx
- packages/components/src/components/tree-select/style/index.less
- packages/components/src/components/tree-select/style/index.ts
- packages/components/src/components/tree/Tree.tsx
- packages/components/src/components/tree/iconUtil.tsx
- packages/components/src/components/tree/style/index.less
- packages/components/src/utils/iconUtil.tsx
- packages/components/src/utils/reactNode.ts
- packages/tokens/properties/color/background.json
- packages/tokens/properties/color/border.json
- packages/website/src/components/functional/tree/demos/index.tsx
- packages/website/src/components/functional/treeSelect/demos/index.less
- packages/website/src/components/functional/treeSelect/demos/multiple.tsx
- packages/website/src/components/functional/treeSelect/demos/single.tsx
- packages/website/src/components/functional/treeSelect/index.zh-CN.md
- yarn.lock
> feat(components,website,tokens): add treeSelect

- packages/components/package.json
- packages/icons/package.json
- packages/tokens/package.json
- packages/website/src/develop/changelog/components.en-US.md
- packages/website/src/develop/changelog/components.zh-CN.md
- packages/website/src/develop/changelog/tokens.zh-CN.md
affects: @gio-design/components, @gio-design/icons, @gio-design/tokens, website
> docs: @gio-design 20.9.2 change log

- packages/website/src/develop/changelog/components.zh-CN.md
> docs: update 20.9.2 change log

- packages/components/src/components/alert/style/index.ts
- packages/components/src/components/avatar/style/index.ts
- packages/components/src/components/banner/style/index.ts
- packages/components/src/components/date-picker/style/index.ts
- packages/components/src/components/drawer/style/index.ts
- packages/components/src/components/dropdown/style/index.ts
- packages/components/src/components/input/style/index.ts
- packages/components/src/components/list/style/index.ts
- packages/components/src/components/loading/style/index.ts
- packages/components/src/components/pagination/style/index.ts
- packages/components/src/components/popconfirm/style/index.ts
- packages/components/src/components/popover/style/index.ts
- packages/components/src/components/progress/style/index.ts
- packages/components/src/components/searchBar/style/index.ts
- packages/components/src/components/select/style/index.ts
- packages/components/src/components/skeleton/style/index.ts
- packages/components/src/components/table/style/index.ts
- packages/components/src/components/tabnav/style/index.ts
- packages/components/src/components/tabs/style/index.ts
- packages/components/src/components/tag/style/index.ts
- packages/components/src/components/toast/style/index.ts
- packages/components/src/components/toggles/style/index.ts
- packages/components/src/components/tooltip/style/index.ts
| 🇺🇸 English |     fix some components can't be loaded on demand bug.      |
| 🇨🇳 Chinese |     修复部分组件无法按需加载问题。      |
> fix: fix on demand loading bug

- packages/components/package.json
- packages/icons/package.json
- packages/tokens/package.json
- packages/website/src/develop/changelog/components.en-US.md
- packages/website/src/develop/changelog/components.zh-CN.md
- packages/website/src/develop/changelog/icons.en-US.md
- packages/website/src/develop/changelog/icons.zh-CN.md
- packages/website/src/develop/changelog/tokens.zh-CN.md
affects: @gio-design/components, @gio-design/icons, @gio-design/tokens, website
> docs: @gio-design/components 20.9.6 change log

- packages/components/src/components/table/Table.tsx
- packages/components/src/components/table/hook/usePagination.tsx
- packages/components/src/components/table/hook/useSelection.tsx
- packages/components/src/components/table/style/index.less
- packages/website/src/components/functional/table/demo/pagination.tsx
| 🇺🇸 English |   update table return type from ReactNode to ReactElement        |
| 🇨🇳 Chinese |   将 table 返回类型ReactNode 改为 ReactElement        |
> fix(table): update table return type from ReactNode to ReactElement

- packages/components/src/components/loading/style/index.less
loading mask style error
loading 的 蒙层样式错误
loading mask style error
| 🇺🇸 English |    loading mask style error        |
| 🇨🇳 Chinese |   loading 的 蒙层样式错误        |
> fix(loading): loading mask style error

- packages/components/src/components/date-picker/__tests__/__snapshots__/data-picker.spec.js.snap
- packages/components/src/components/date-picker/datePicker.tsx
- packages/components/src/components/date-picker/dateRangePicker.tsx
- packages/components/src/components/date-picker/style/decadePanel.less
- packages/components/src/components/date-picker/style/index.less
- packages/components/src/components/date-picker/style/monthPanel.less
- packages/components/src/components/date-picker/style/yearPanel.less
#246 
#261
| 🇺🇸 English | replace svg icon with fonticon，refactor zindex          |
| 🇨🇳 Chinese |  先去掉切换的svg icon改成font，将zindex放入token中       |
> style(DatePicker): refactor icon & zIndex

- packages/components/package.json
- packages/icons/package.json
- packages/tokens/package.json
- packages/website/src/develop/changelog/components.en-US.md
- packages/website/src/develop/changelog/components.zh-CN.md
- packages/website/src/develop/changelog/icons.en-US.md
- packages/website/src/develop/changelog/icons.zh-CN.md
- packages/website/src/develop/changelog/tokens.zh-CN.md
- yarn.lock
> docs: @gio-design/components 20.9.7 change log

- packages/components/src/components/searchBar/index.tsx
- packages/components/src/components/searchBar/interfaces.ts
| 🇺🇸 English | add placeholder prop          |
| 🇨🇳 Chinese |  添加占位符参数         |
> feat(searchbar): add placeholder prop

- packages/components/package.json
- packages/icons/package.json
- packages/tokens/package.json
- packages/website/src/develop/changelog/components.en-US.md
- packages/website/src/develop/changelog/components.zh-CN.md
> docs: @gio-design/components 20.10.0 change log

- packages/components/package.json
- packages/icons/package.json
- packages/tokens/package.json
- packages/website/src/develop/changelog/components.en-US.md
- packages/website/src/develop/changelog/components.zh-CN.md
- packages/website/src/develop/changelog/icons.zh-CN.md
affects: @gio-design/components, @gio-design/icons, @gio-design/tokens, website
fix changelog and version numbers;
> docs: @gio-design/components 20.10.1 change log

- packages/components/package.json
- packages/icons/package.json
- packages/website/src/develop/changelog/components.en-US.md
- packages/website/src/develop/changelog/components.zh-CN.md
- packages/website/src/develop/changelog/icons.zh-CN.md
> docs: @gio-design/components 20.10.2 change log

- packages/components/src/components/form/style/index.less
根据stylelint的提示，修改了form组件中index.less中部分属性的顺序
> style(form): 根据stylelint的提示，修改了form组件中index.less中部分属性的顺序

- packages/components/package.json
- packages/icons/package.json
- packages/website/src/develop/changelog/components.en-US.md
- packages/website/src/develop/changelog/components.zh-CN.md
- packages/website/src/develop/changelog/icons.en-US.md
- packages/website/src/develop/changelog/icons.zh-CN.md
> docs: @gio-design/components 20.10.3 change log

- packages/components/package.json
- packages/icons/package.json
- packages/website/src/develop/changelog/components.en-US.md
- packages/website/src/develop/changelog/components.zh-CN.md
- packages/website/src/develop/changelog/icons.en-US.md
- packages/website/src/develop/changelog/icons.zh-CN.md
> docs: @gio-designs/components release-20.10.4 change log

- packages/components/src/components/alert/__tests__/alert.test.js
Unit test of alert component is added
> test(alert): unit test of alert component is added

- packages/components/src/components/form/Item.tsx
- packages/components/src/components/form/ItemLabel.tsx
- packages/components/src/components/form/__test__/form.test.tsx
- packages/components/src/components/form/__test__/item.test.tsx
- packages/website/src/components/functional/form/demo/base.tsx
now will render colon in any layout
> fix(form): fix colon not render issue

- packages/components/package.json
- packages/icons/package.json
- packages/website/src/develop/changelog/components.en-US.md
- packages/website/src/develop/changelog/components.zh-CN.md
- packages/website/src/develop/changelog/icons.en-US.md
- packages/website/src/develop/changelog/icons.zh-CN.md
> docs: @gio-design/components 20.10.5 change log

- packages/components/package.json
- packages/icons/package.json
- packages/website/src/develop/changelog/components.en-US.md
- packages/website/src/develop/changelog/components.zh-CN.md
- packages/website/src/develop/changelog/icons.en-US.md
- packages/website/src/develop/changelog/icons.zh-CN.md
Reverts growingio/gio-design#354
> revert: docs: @gio-design/components 20.10.5 change log

- packages/components/src/components/modal/CalloutModal.tsx
- packages/components/src/components/modal/Modal.tsx
- packages/components/src/components/modal/__test__/__snapshots__/staticFunc.test.tsx.snap
- packages/components/src/components/modal/__test__/staticFunc.test.tsx
- packages/components/src/components/modal/callout.tsx
- packages/components/src/components/modal/index.tsx
- packages/components/src/components/modal/interface.ts
- packages/components/src/components/modal/style/callout.less
- packages/components/src/components/modal/style/index.less
- packages/components/src/components/modal/style/mixin.less
- packages/components/src/components/modal/utils.ts
- packages/components/src/index.ts
- packages/website/src/components/functional/modal/demo/calllout.tsx
- packages/website/src/components/functional/modal/demo/functionCallModal.tsx
- packages/website/src/components/functional/modal/demo/reference.tsx
- packages/website/src/components/functional/modal/index.zh-CN.md
> feat(components): add Modal.staticFuncs

- .eslintrc.js
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-shadow.md
> refactor: fix eslint no-shadow rule cause incorrect error'

- packages/components/src/components/alert/__tests__/alert.test.js
improve test coverage to 100%
| 🇺🇸 English |      improve test coverage of Alert component to 100%     |
| 🇨🇳 Chinese |     将alert组件的单元测试覆盖率提升到100%      |
> test(alert): improve test coverage to 100%

- packages/components/src/components/upload/interface.ts
- packages/components/src/components/upload/triggers/AvatarTrigger.tsx
- packages/components/src/components/upload/triggers/CardTrigger.tsx
- packages/components/src/components/upload/triggers/DragTrigger.tsx
- packages/components/src/components/upload/triggers/InputTrigger.tsx
- packages/components/src/components/upload/utils.ts
> refactor(componnets): check and fix lint errors in upload component

- packages/components/src/components/tag/Tag.tsx
- packages/components/src/components/tag/__tests__/__snapshots__/Tag.test.js.snap
- packages/components/src/components/tag/interface.ts
> Tag fix style lint

- .eslintrc.js
- packages/components/src/components/form/Form.tsx
- packages/components/src/components/form/__test__/form.test.tsx
- packages/components/src/components/form/__test__/item.test.tsx
- packages/components/src/components/form/__test__/util.test.tsx
- packages/components/src/components/form/util.ts
- packages/components/src/components/grid/style/index.less
test(form): improve test coverage and fix lint issue #297
> test(form): imporve test coverage and fix style line isuess

- packages/components/src/components/modal/Modal.tsx
- packages/components/src/components/modal/StepModal.tsx
- packages/components/src/components/modal/interface.ts
- packages/website/src/components/functional/modal/demo/asyncConfirm.tsx
- packages/website/src/components/functional/modal/demo/asyncStepModal.tsx
- packages/website/src/components/functional/modal/index.zh-CN.md
- StepModal
- StepModal  的 onNext, onBack 支持异步调用，可打断下一步的执行
> refactor(components): support async function in StepModal's step change

- packages/components/src/components/form/__test__/form.test.tsx
- packages/components/src/components/form/__test__/item.test.tsx
> test(form): improve test coverage

- packages/components/src/components/avatar/AvatarGroup.tsx
- packages/components/src/components/avatar/__tests__/Avatar.test.js
- packages/components/src/components/avatar/__tests__/AvatarGroup.test.js
- 头像
- 提升组件单元测试率
---
- Avatar
- improve test coverage
> test(avatar): improve test coverage to 99%

- packages/components/src/components/dropdown/__test__/Dropdown.test.js
- packages/components/src/components/skeleton/Skeleton.tsx
- packages/components/src/components/skeleton/__test__/Skeleton.test.js
- packages/components/src/components/tab-nav/__test__/TabNav.test.js
- packages/components/src/components/tabs/__tests__/Tabs.test.js
- packages/components/src/components/tooltip/Tooltip.tsx
- packages/components/src/components/tooltip/__tests__/Tooltip.test.js
- packages/components/src/components/tooltip/placements.ts
> test(skeleton,tooltip,tabs,dropdown,tabnav): improve test coverage

- .eslintrc.js
- packages/components/src/components/avatar/__tests__/Avatar.test.js
- packages/components/src/components/avatar/__tests__/AvatarGroup.test.js
- packages/components/src/components/date-picker/style/index.less
- packages/components/src/components/dropdown/__test__/Dropdown.test.js
- packages/components/src/components/loading/__test__/Loading.test.js
- packages/components/src/components/popconfirm/__tests__/Popconfirm.test.js
- packages/components/src/components/popover/__tests__/Popover.test.js
- packages/components/src/components/skeleton/__test__/Skeleton.test.js
- packages/components/src/components/table/Table.tsx
- packages/components/src/components/table/Title.tsx
- packages/components/src/components/table/__test__/Table.test.js
- packages/components/src/components/table/__test__/TableEllipsisTooltip.test.js
- packages/components/src/components/table/__test__/TableFilter.test.js
- packages/components/src/components/table/__test__/TableGroup.test.js
- packages/components/src/components/table/__test__/TablePagination.test.js
- packages/components/src/components/table/__test__/TableSelection.test.js
- packages/components/src/components/table/__test__/TableSorter.test.js
- packages/components/src/components/table/__test__/TableUtils.test.js
- packages/components/src/components/table/hook/useEllipsisTooltip.tsx
- packages/components/src/components/table/hook/useFilter.tsx
- packages/components/src/components/table/hook/useSelection.tsx
- packages/components/src/components/table/hook/useSorter.tsx
- packages/components/src/components/table/interface.ts
- packages/components/src/components/table/style/index.less
- packages/components/src/components/table/utils.ts
- packages/components/src/components/tooltip/__tests__/Tooltip.test.js
- packages/components/src/utils/test/index.ts
- packages/website/src/components/functional/table/index.zh-CN.md
affects: @gio-design/components 
提升测试覆盖率。
修复当Table内容为空时，鼠标hover 会变色的问题。
定义当设置ellipsis时与render 方法之间的关系。
> test(table): improve test coverage to 99%

- packages/components/src/components/button/__tests__/__snapshots__/button.test.js.snap
- packages/components/src/components/button/__tests__/button.test.js
- packages/website/src/components/basic/button/demos/primary.tsx
improve test coverage to 99%
- 按钮
- 提升button组件单元测试覆盖率
---
- button
- improve test coverage of button
> test(button): improve test coverage to 99%

- packages/components/src/components/tree/__tests__/Tree.test.js
- packages/components/src/components/tree/__tests__/__snapshots__/Tree.test.js.snap
- packages/components/src/components/tree/iconUtil.tsx
提高tree组件的测试覆盖率
---
improve tree component test coverage to 100%
> test(compontents): tree test

- packages/components/src/components/checkbox/__tests__/__snapshots__/group.test.js.snap
- packages/components/src/components/checkbox/__tests__/group.test.js
improve test coverage to 99%
- 单选框
- 提升组件单元测试覆盖率
---
- checkbox
- improve test coverage to 99%
> test(checkbox): improve test coverage to 99%

- packages/components/src/components/modal/CalloutModal.tsx
- packages/components/src/components/modal/__test__/__snapshots__/staticFunc.test.js.snap
- packages/components/src/components/modal/__test__/modal.test.js
- packages/components/src/components/modal/__test__/staticFunc.test.js
- packages/components/src/components/modal/__test__/stepModal.test.js
- packages/components/src/components/modal/__test__/steps.js
- packages/components/src/components/modal/callout.tsx
- packages/website/src/components/functional/modal/demo/calllout.tsx
> test(modal): improve modal test coverage

- packages/components/src/components/dropdown/Dropdown.tsx
- packages/website/src/components/functional/dropdown/demo/base.tsx
ISSUES CLOSED: #394
- 下拉列表
- 修复点击后onVisibleChange没有被调用
---
- Dropdown
-  fix onVisibleChange not be call after click
> fix(dropdown): fix onVisibleChange not be call after click

- packages/components/src/components/banner/__tests__/Banner.spec.js
improve test coverage to 99%
- Banner
- 提升单元测试覆盖率
---
- Banner
- improve test coverage to 99%
> test(banner): improve test coverage to 99%

- packages/components/src/components/form/Form.tsx
- packages/components/src/components/form/Item.tsx
add style prop to Form and Item
- 表单
- 给Form组件和Form.Item增加style属性
---
- Form
- add style prop to Form and Item
> feat(form): add style prop to Form and Item

- packages/components/package.json
- packages/components/src/components/radio/__tests__/__snapshots__/group.test.js.snap
- packages/components/src/components/radio/__tests__/group.test.js
- yarn.lock
> test(radio): imporve radio's test coverage

- packages/components/src/components/loading/index.tsx
fix the eslint problem
- 加载中
- 修复eslint问题
---
- loading
- fix the eslint problem
> refactor(loading): fix the eslint problem

- packages/components/src/components/pagination/ until.ts
- packages/components/src/components/pagination/Pagination.tsx
- packages/components/src/components/pagination/__test__/Pagination.test.js
- packages/components/src/components/pagination/__test__/__snapshots__/Pagination.test.js.snap
fix the eslint error of pagination
- 分页
- 修复pagination组件的eslint错误
---
- pagination
- fix the eslint error of pagination
> refactor(pagination): fix the eslint error of pagination

- packages/components/src/components/table/__test__/TableSelection.test.js
- packages/components/src/components/table/hook/useSelection.tsx
- packages/components/src/components/table/interface.ts
- packages/website/src/components/functional/table/demo/pagination.tsx
- packages/website/src/components/functional/table/index.zh-CN.md
- 列表
- 添加 getCheckboxProps 参数
---
- Table
- add getCheckboxProps prop
> feat(table): add getCheckboxProps prop

- packages/components/src/components/select/Select.tsx
- 组件 1
- 某某
- 某某
---
- Component 1
- xxxxx
- xxxxx
> fix: fix auto width style issue

- packages/components/src/components/list/Group.tsx
- packages/components/src/components/list/core.tsx
- packages/components/src/components/list/interface.ts
- packages/components/src/components/list/list.tsx
- packages/components/src/components/list/option.tsx
- packages/components/src/components/list/style/base.less
- packages/website/src/components/functional/list/demo/avatar.tsx
- packages/website/src/components/functional/list/demo/base.tsx
- packages/website/src/components/functional/list/demo/drag.tsx
- packages/website/src/components/functional/list/demo/group.tsx
- packages/website/src/components/functional/list/demo/withIcon.tsx
- packages/website/src/components/functional/list/index.zh-CN.md
ISSUES CLOSED: #222, #260
- 组件 list
- 提供onClick参数
- 增加padding
---
- Component list
- provide onClick param
- add padding style
> refactor(list): add onClick prop and padding style

- .eslintrc.js
- packages/components/src/components/search-bar/__tests__/searchbar.test.js
- packages/components/src/components/search-bar/index.tsx
- packages/components/src/components/skeleton/Skeleton.tsx
- packages/components/src/components/table/FilterPopover.tsx
- packages/components/src/components/table/Table.tsx
- packages/components/src/components/table/Title.tsx
- packages/components/src/components/table/__test__/Table.test.js
- packages/components/src/components/table/__test__/TableEllipsisTooltip.test.js
- packages/components/src/components/table/__test__/TableFilter.test.js
- packages/components/src/components/table/__test__/TableGroup.test.js
- packages/components/src/components/table/__test__/TablePagination.test.js
- packages/components/src/components/table/__test__/TableSelection.test.js
- packages/components/src/components/table/__test__/TableSorter.test.js
- packages/components/src/components/table/hook/useEllipsisTooltip.tsx
- packages/components/src/components/table/hook/useFilter.tsx
- packages/components/src/components/table/hook/useSelection.tsx
- packages/components/src/components/table/utils.ts
fix the stylelint and eslint error
- 搜索框
- 修复stylelint和eslint错误
- 骨架图
- 修复stylelint和eslint错误
- 表格
- 修复stylelint和eslint错误
---
- search-bar
- fix the stylelint and eslint error
- skeleton
- fix the stylelint and eslint error
- table
- fix the stylelint and eslint error
> refactor(search-bar/skeleton/table): fix the stylelint and eslint error

- packages/components/src/components/select/Select.tsx
- 组件 1
- 某某
- 某某
---
- Component 1
- xxxxx
- xxxxx
Closes #451
> fix: fix umpty value check logic

- packages/components/src/components/select/Select.tsx
- packages/components/src/components/select/__tests__/Select.test.js
- packages/components/src/components/select/style/index.less
- 组件 1
- 某某
- 某某
---
- Component 1
- xxxxx
- xxxxx
> Select fix input caused style error

- .eslintrc.js
- packages/components/src/components/time-picker/Panel.tsx
- packages/components/src/components/time-picker/Select.tsx
- packages/components/src/components/time-picker/TimePicker.tsx
- packages/components/src/components/time-picker/index.tsx
- packages/components/src/components/time-picker/interface.ts
- packages/components/src/components/toast/__tests__/index.test.js
- packages/components/src/components/toast/index.tsx
- packages/components/src/components/toggles/toggles.tsx
- packages/components/src/components/tooltip/Tooltip.tsx
- packages/components/src/components/tooltip/__tests__/Tooltip.test.js
- packages/components/src/components/tooltip/index.tsx
- packages/components/src/components/tooltip/placements.ts
- yarn.lock
fix stylelint and eslint error
- 时分选择器
- 修复stylelint和eslint错误
- 全局提示
- 修复stylelint和eslint错误
- 开关
- 修复stylelint和eslint错误
- 文字提示
- 修复stylelint和eslint错误
---
- time-picker
- fix stylelint and eslint error
- toast
- fix stylelint and eslint error
- toggles
- fix stylelint and eslint error
- tooltip
- fix stylelint and eslint error
> refactor(time-picker/toast/toggles/tooltip): fix stylelint and eslint error

- packages/components/src/components/select/Select.tsx
- packages/components/src/components/select/style/index.less
- packages/website/src/components/functional/select/demos/freeinput.tsx
- packages/website/src/components/functional/select/demos/highlight.tsx
- packages/website/src/components/functional/select/demos/multiple.tsx
- packages/website/src/components/functional/select/demos/single.tsx
Fix sellector no width  when unselected 
Closes #462
> fix: Select style bug and placeholder not wokring

- packages/components/src/components/list/core.tsx
- packages/components/src/components/list/interface.ts
- packages/components/src/components/list/list.tsx
- packages/components/src/components/list/normal.tsx
- packages/components/src/components/list/style/base.less
- packages/components/src/components/list/style/option.less
- packages/components/src/components/select/__tests__/Select.test.js
- packages/website/src/components/functional/list/demo/base.tsx
- packages/website/src/components/functional/list/index.zh-CN.md
ISSUES CLOSED: #222
- 列表
- 添加 stateless 参数
- 添加 padding 
---
- List
-  add stateless prop
-  add padding style
> feat(list): add stateless prop, add padding style, use autosize width

- packages/components/src/components/table/Empty.tsx
- packages/components/src/components/table/Table.tsx
- packages/components/src/components/table/hook/useEllipsisTooltip.tsx
- packages/components/src/components/table/style/index.ts
- packages/components/src/components/table/utils.ts
ISSUES CLOSED: #409
- 列表
- 引入依赖组件样式
---
- Table
-  import dependence components style
> fix(table): import dependence components style

- packages/components/package.json
- packages/website/src/develop/changelog/components.en-US.md
- packages/website/src/develop/changelog/components.zh-CN.md
- 组件 1
- 某某
- 某某
---
- Component 1
- xxxxx
- xxxxx
> docs(release): @gio-design/components 20.11.1 change log

- packages/components/src/components/avatar/Avatar.tsx
- packages/components/src/components/avatar/__tests__/Avatar.test.js
- packages/components/src/components/avatar/__tests__/__snapshots__/AvatarGroup.test.js.snap
- 头像
- 修复头像不能触发下拉列表
---
- Avatar
- fix avatar can't be trigger
> fix(avatar): avatar can't trigger dropdown

- packages/components/package.json
- packages/icons/package.json
- packages/website/src/develop/changelog/components.en-US.md
- packages/website/src/develop/changelog/components.zh-CN.md
- packages/website/src/develop/changelog/icons.en-US.md
- packages/website/src/develop/changelog/icons.zh-CN.md
> docs(release): @gio-design/components, @gio-design/icons

- packages/components/src/components/list/core.tsx
- packages/components/src/components/list/list.tsx
- packages/website/src/components/functional/list/demo/avatar.tsx
- packages/website/src/components/functional/list/demo/base.tsx
- packages/website/src/components/functional/list/demo/drag.tsx
- packages/website/src/components/functional/list/demo/group.tsx
- packages/website/src/components/functional/list/demo/withIcon.tsx
> fix(website,components): 修复list定高问题

- packages/components/src/components/button/style/mixin.less
> style(components): button 默认高度修复

- packages/components/package.json
- packages/tokens/package.json
- packages/website/src/develop/changelog/components.en-US.md
- packages/website/src/develop/changelog/components.zh-CN.md
- packages/website/src/develop/changelog/tokens.zh-CN.md
> docs(website,tokens,components): @gio-design@20.11.3

- packages/components/src/components/date-picker/__tests__/__snapshots__/data-picker.spec.js.snap
- packages/components/src/components/input/Input.tsx
- packages/components/src/components/input/__tests__/__snapshots__/input.test.js.snap
- packages/components/src/components/input/__tests__/input.test.js
- packages/components/src/components/input/style/index.less
- packages/components/src/components/pagination/__test__/__snapshots__/Pagination.test.js.snap
- packages/components/src/components/search-bar/__tests__/__snapshots__/searchbar.test.js.snap
- packages/components/src/components/search-bar/__tests__/searchbar.test.js
- packages/components/src/components/search-bar/style/index.less
- packages/website/src/components/basic/input/demo/InputNumber.tsx
- packages/website/src/components/basic/input/demo/Password.tsx
- 输入框
- 更换居中样式代码
- 搜索框 
- 默认宽度100%
---
- Input
-  update mediate code of input
- searchbar 
-  set default width 100%
> style(input, searchbar): update mediate code of input

- packages/components/src/components/menu/style/index.less
fix some problems in menu
- 导航菜单
- 修复第一个submenu不应该有padding-top的问题
---
- Menu
- Fixed the problem that the first submenu should not have padding top
> fix(menu): fix some problems in menu

- packages/components/src/components/select/style/index.ts
ISSUES CLOSED: #514
- 选择器
- 引入依赖组件样式
---
- Select
- import dependence components style
> style(select): import dependence components style

- .eslintrc.js
- packages/components/src/components/cascader/__tests__/cascader.test.js
- packages/components/src/components/cascader/__tests__/menu.test.js
- packages/components/src/components/cascader/helper.ts
- packages/components/src/components/cascader/menu-item.tsx
- packages/components/src/components/cascader/menu.tsx
- packages/components/src/components/cascader/single-menu.tsx
- packages/components/src/components/cascader/style/index.less
- packages/components/tsconfig.json
- packages/website/src/components/basic/cascader/demo/group.tsx
- packages/website/src/components/basic/cascader/demo/search.tsx
> feat: cascader align bottom

- packages/components/src/components/menu/style/index.less
- packages/components/src/components/time-picker/style/index.ts
add a index.ts to export style
- 时分选择器
- 添加一个index.ts文件，方便style引入
- 导航菜单
- 上个pr调试的时候加了一个border，没注意改回来，被merge了
---
- time-picker
- Add one index.ts File, convenient for Style Introduction
- A border was added when debugging PR, but it was merged
> style(memu,time-picker): add a index.ts to export style

- packages/components/package.json
- packages/tokens/package.json
- packages/website/src/develop/changelog/components.en-US.md
- packages/website/src/develop/changelog/components.zh-CN.md
- packages/website/src/develop/changelog/tokens.zh-CN.md
> docs(release): @gio-design@20.11.4 changelog

- packages/components/package.json
- packages/tokens/package.json
- packages/website/src/develop/changelog/components.en-US.md
- packages/website/src/develop/changelog/components.zh-CN.md
- packages/website/src/develop/changelog/tokens.zh-CN.md
Reverts growingio/gio-design#550
> revert: docs(release): @gio-design@20.11.4 changelog

- packages/components/package.json
- packages/tokens/package.json
- packages/website/src/develop/changelog/components.en-US.md
- packages/website/src/develop/changelog/components.zh-CN.md
- packages/website/src/develop/changelog/tokens.zh-CN.md
> docs(release): gio-design@20.11.5 changelog

- packages/components/src/components/upload/Upload.tsx
- packages/components/src/components/upload/interface.ts
- packages/components/src/components/upload/triggers/ButtonTrigger.tsx
- packages/components/src/components/upload/utils.ts
- packages/website/src/components/functional/upload/demos/card.tsx
- Upload
- support file prop
- support sizeContext in button trigger
---
> feat(upload): support new features

- packages/components/src/components/menu/Menu.tsx
- packages/components/src/components/menu/MenuContext.ts
- packages/components/src/components/menu/MenuItem.tsx
- packages/components/src/components/menu/MenuTitle.tsx
- packages/components/src/components/menu/SubMenu.tsx
- packages/components/src/components/menu/__tests__/__snapshots__/menu.test.js.snap
- packages/components/src/components/menu/index.tsx
- packages/components/src/components/menu/interface.ts
- packages/components/src/components/menu/style/index.less
- packages/components/src/components/modal/__test__/staticFunc.test.js
- packages/website/src/components/basic/menu/demos/vertical.tsx
- packages/website/src/components/basic/menu/index.zh-CN.md
- Menu
- 修正 Menu 组件中 ul 的 margin 问题
- SubMenu 下的 MenuItem 将随 SubMenu 是否有 icon 进行缩进的变化
> feat(menu): fix menu style

- packages/components/src/components/date-picker/datePicker.tsx
- packages/components/src/components/date-picker/dateRangePicker.tsx
- packages/components/src/components/date-picker/interface.tsx
- packages/components/src/components/date-picker/style/index.less
- packages/components/src/index.ts
export date-picker from index.ts
- 日期选择器
- 将date-picker从index中导出
- 将onChange和onSelect设置为可选参数
- 让dropdown失焦隐藏
---
- DatePicker
- export date-picker from index.ts
- Set onchange and onselect as optional parameters
- Let dropdown lose focus and hide
> perf(date-picker): export date-picker from index.ts

- packages/components/src/components/checkbox/checkbox.tsx
- packages/components/src/components/search-bar/index.tsx
- packages/components/src/components/select/style/index.less
let select list to fit by self
- 选择器
- 给下拉的list一个最大高度
- 多选框
- 让checkbox支持非受控模式
- 搜索框
- 去除搜索框搜索记录高亮以及搜索记录匹配
---
- Select
- Give the drop-down list a maximum height
- Checkbox
- Making checkboxes support uncontrolled mode
- SearchBar
- Remove the search box, search record highlight and search record matching
> perf(select): let select list to fit by self

- packages/components/src/components/toast/interface.ts
- packages/components/src/components/toast/useToast/index.tsx
- packages/website/src/components/basic/toast/demo/useToast.tsx
> refactor(toast): fix useToast ts interface

- packages/components/package.json
- packages/components/src/components/tooltip/Tooltip.tsx
- packages/components/src/components/tooltip/interface.ts
- packages/website/src/components/basic/tooltip/index.zh-CN.md
ISSUES CLOSED: #500
- 文字提示
- 添加 autoAdjustOverflow 参数
---
- Tooltip
- add autoAdjustOverflow prop
> feat(tooltip): add autoAdjustOverflow prop

- package.json
- packages/components/package.json
- packages/tokens/package.json
- packages/website/src/develop/changelog/components.zh-CN.md
- packages/website/src/develop/changelog/tokens.zh-CN.md
- yarn.lock
> docs(release): gio-design 20.12.0 changelog

- packages/components/src/components/list/style/base.less
- packages/components/src/components/table/FilterPopover.tsx
- packages/components/src/components/table/__test__/Table.test.js
- packages/components/src/components/table/style/index.less
- 列表
- 更新列表筛选样式
---
- Table
-  update table filter style
> style(table): update table filter style

- packages/components/src/components/cascader/single-menu.tsx
- packages/website/src/components/basic/cascader/demo/custom-group-name.tsx
- packages/website/src/components/basic/cascader/index.zh-CN.md
> fix: 修复 groupName 不显示的问题

- packages/components/package.json
- packages/website/src/develop/changelog/components.zh-CN.md
> docs(release): version 20.12.1 changelog

- packages/components/src/components/list/style/option.less
- packages/tokens/properties/shadow.json
修改box-shadow值
list disabled状态不该有hover效果
> style(tokens,components): 修改box-shadow值、list disabled状态不该有hover效果

- packages/components/src/components/table/Table.tsx
- packages/components/src/components/table/hook/useHackOnRow.tsx
- packages/components/src/components/table/interface.ts
- packages/website/src/components/functional/table/demo/base.tsx
- packages/website/src/components/functional/table/index.zh-CN.md
- 列表
- 添加 hackRowEvent 功能
- 将 style，className应用到最外层
---
- Table
- add hackRowEvent props
- Apply style, className to the outermost layer
> feat(table): add hackRowEvent props

- packages/components/src/components/alert/alert.tsx
- packages/components/src/components/alert/interfaces.ts
@gio-design/components@20.12.2
- 警告提示
- 添加style参数
---
@gio-design/components@20.12.2
- Alert
- add style props
- xxxxx
> feat(alert): add style props

- packages/components/src/components/sign/Number.tsx
- packages/components/src/components/sign/Sign.tsx
- packages/components/src/components/sign/__tests__/__snapshots__/sign.test.js.snap
- packages/components/src/components/sign/interface.ts
- packages/components/src/components/sign/style/index.less
- packages/website/src/components/basic/sign/demos/sign.tsx
- packages/website/src/components/basic/sign/index.zh-CN.md
- 标记
- 添加offset参数
---
- Component 1
- add offset prop
> feat(sign): add offset prop

- packages/components/src/components/avatar/Avatar.tsx
- packages/components/src/components/avatar/__tests__/Avatar.test.js
- packages/components/src/components/avatar/__tests__/AvatarGroup.test.js
- packages/components/src/components/avatar/__tests__/__snapshots__/Avatar.test.js.snap
- packages/components/src/components/avatar/__tests__/__snapshots__/AvatarGroup.test.js.snap
- packages/components/src/components/avatar/style/index.less
- packages/components/src/components/avatar/style/index.ts
- 头像
- 修复缩放错误
- 首字母大写
---
- Avatar
- fix scale error
- capitalise the first letter
> style(avatar): fix scale error, capitalise the first letter

- packages/components/src/components/sign/Number.tsx
- packages/components/src/components/sign/Sign.tsx
- packages/components/src/components/sign/__tests__/__snapshots__/sign.test.js.snap
- packages/components/src/components/sign/interface.ts
- packages/components/src/components/sign/style/index.less
- packages/website/src/components/basic/sign/demos/sign.tsx
- packages/website/src/components/basic/sign/index.zh-CN.md
Reverts growingio/gio-design#620
> revert: feat(sign): add offset prop

- packages/components/package.json
- packages/icons/package.json
- packages/website/src/develop/changelog/components.zh-CN.md
- packages/website/src/develop/changelog/icons.zh-CN.md
> docs(release): version 20.12.2 changelog

- packages/components/package.json
- packages/icons/package.json
- packages/website/src/develop/changelog/components.zh-CN.md
- packages/website/src/develop/changelog/icons.zh-CN.md
Reverts growingio/gio-design#628
> revert: docs(release): version 20.12.2 changelog

- packages/components/package.json
- packages/website/src/develop/changelog/components.zh-CN.md
> docs(release): version 20.12.3 change log

- packages/components/src/components/drawer/style/drawer.less
- packages/components/src/components/modal/style/mixin.less
加快动画效果
- 弹窗
- 将动画时间由0.3s改为0.2s
- 抽屉
- 将动画时间由0.3s改为0.2s
---
- Modal
- Change the animation time from 0.3s to 0.2s
- Drawer
- Change the animation time from 0.3s to 0.2s
> style(modal and drawer): 加快动画效果

- packages/components/src/components/input/style/index.less
- Input
- 设置input的min-width为 0，否则在某些要求设置 input width的情况下会出现样式问题
> style(input): add min-width for input

- packages/components/package.json
- packages/website/src/develop/changelog/components.zh-CN.md
> docs(release): version 20.12.4 change log

- packages/components/package.json
- packages/website/src/develop/changelog/components.zh-CN.md
> docs(release): version 20.12.5 changelog

- packages/components/src/components/tooltip/style/index.less
- 气泡卡片
- 添加 word break
---
- tooltip
- add word break
> style(tooltip): add word break

- packages/components/package.json
- packages/website/src/develop/changelog/components.zh-CN.md
> docs(release): version 20.12.6 changelog

- src/components/checkbox/checkbox.tsx
修复checkbox在账号申请中的bug
- 多选框
- 修复checkbox的bug
---
- Checkbox
- Fix the bug of checkbox
> fix(checkbox): 修复checkbox组件的bug

- .gitignore
- package.json
- src/components/avatar/Avatar.tsx
- src/components/avatar/__tests__/Avatar.test.js
- src/components/avatar/style/index.less
- src/components/banner/__tests__/__snapshots__/Banner.spec.js.snap
- src/components/button/__tests__/__snapshots__/button.test.js.snap
- src/components/checkbox/__tests__/__snapshots__/checkbox.test.js.snap
- src/components/checkbox/__tests__/__snapshots__/group.test.js.snap
- src/components/checkbox/checkbox.tsx
- src/components/drawer/__tests__/__snapshots__/drawer.test.js.snap
- src/components/input/__tests__/__snapshots__/input.test.js.snap
- src/components/modal/__test__/__snapshots__/stepModal.test.js.snap
- src/components/pagination/__test__/__snapshots__/Pagination.test.js.snap
- src/components/progress/__tests__/__snapshots__/Progress.test.js.snap
- src/components/search-bar/__tests__/__snapshots__/searchbar.test.js.snap
- src/components/select/__tests__/__snapshots__/Select.test.js.snap
- src/components/skeleton/__test__/__snapshots__/Skeleton.test.js.snap
- src/components/tree-select/__tests__/__snapshots__/tree-select.test.js.snap
- src/components/tree-select/iconUtil.tsx
- src/components/tree/__tests__/__snapshots__/Tree.test.js.snap
- src/components/upload/__tests__/__snapshots__/actions.test.js.snap
- src/components/upload/__tests__/__snapshots__/preview.test.js.snap
- yarn.lock
use the default avatar when src and children do not exist.
- 升级@gio-design/icons库版本为v21.1.0
> feat(avatar): add a default avatar style

- src/components/input/InputNumber.tsx
- src/components/toggles/style/index.less
修复input.number输入框能输入字符串的问题
修复toogles文字垂直不居中的问题
> fix(input): 修复input.number输入框能输入字符串的问题

- src/components/time-picker/TimePicker.stories.tsx
- src/components/time-picker/__tests__/Combobox.test.js
- src/components/time-picker/__tests__/Panel.test.js
- src/components/time-picker/__tests__/Select.test.js
- src/components/time-picker/__tests__/TimePicker.test.js
- src/components/time-picker/__tests__/__snapshots__/Combobox.test.js.snap
- src/components/time-picker/__tests__/__snapshots__/Panel.test.js.snap
- src/components/time-picker/__tests__/__snapshots__/TimePicker.test.js.snap
- src/components/time-picker/style/select.less
* test(timepicker) -> 75
* feat(timepicker) 秒级控件demo新增
> test(timepicker): 提升timepicker单测覆盖率至 75

- .storybook/main.js
- package.json
- src/components/card/Card.stories.tsx
- yarn.lock
Add the figma link of card component in card demo.
> docs(card): add design addon for storybook

- package.json
添加package的main字段，在通过import引入的时候，可以直接引入
> docs: 添加package配置文件的main字段

- CHANGELOG.md
- VERSION.md
- package.json
> docs: version 20.2.0 change log

- CHANGELOG.md
- VERSION.md
- package.json
Reverts growingio/gio-design#772
> Revert "docs: version 20.2.0 change log"

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .gitignore
- jest.config.js
- sonar-project.properties
Add sonar project configuration file.
> ci: generate reports for lint and test jobs

- src/components/tooltip/Tooltip.mdx
- src/components/tooltip/Tooltip.stories.tsx
docs(tooltip): add stories and document for tooltip component
> docs(tooltip): add stories and document for tooltip component

- src/components/toast/Toast.mdx
- src/components/toast/Toast.stories.tsx
docs(toast): add stories and document for toast component
> docs(toast): add stories and document for toast component

- src/components/breadcrumb/Breadcrumb.stories.tsx
- src/components/link/Link.stories.tsx
- src/components/toggles/Toggles.stories.tsx
- src/components/tooltip/Tooltip.stories.tsx
docs: add the design diagram to the document
link toggle tooltip breadcrumb
> docs: add the design diagram to the document

- src/components/progress/Progress.mdx
- src/components/progress/Progress.stories.tsx
docs(progress): add stories and document for progress component
> docs(progress): add stories and document for progress component

- src/components/radio/Radio.mdx
- src/components/radio/Radio.stories.tsx
- src/components/radio/style/index.less
1. modifies the text color of the disabled selected state 
2. add stories and document for radio component
> fix(radio): modifies the text color of the disabled selected state

- src/components/modal/style/mask.less
将 fade 的这些动画样式 移到 gio-modal-mask 作用域下 ，原来是 .gio-modal.fade-enter
> fix(modal): style scope error, fix mask do not disappear

- src/components/select/OptionsList/index.tsx
- src/components/select/Select.stories.tsx
- src/components/select/Select.tsx
- src/components/select/VirtualList.tsx
- src/components/select/__tests__/Select.test.js
- src/components/select/hooks/useCacheOption.ts
- src/components/select/interface.ts
- src/components/select/style/index.less
- src/components/select/utils.tsx
the scroll bar is abnormal when the mouse scrolling
当鼠标滚动时，滚动条异常。不能采取监听activeIndex变动的方式，利用keyDown来进行控制
补充test
修复，如果key不变，value变更的情况下，更新内部Map结构
> fix(select): keydown scroll error

- src/components/input/style/index.less
1. 浏览器自动填充密码样式问题
2. disabled状态下hover样式出错
#732,#841
> fix(input): fix auto password input styles error

- src/components/date-picker/style/index.less
close #844. remove input border
> fix(date-picker): remove range-picker border

- VERSION.md
- package.json
add new version 21.3.1 change log
> docs(release): version 21.3.1 change log

- src/components/select/OptionsList/index.tsx
- src/components/select/Select.tsx
- src/components/select/Selector/index.tsx
- src/components/select/__tests__/Select.test.js
- src/components/select/interface.ts
- src/components/select/style/index.less
change searchable to searchType
由于命名不规范
修改searchable 为 searchType: 'normal' | 'inner' | 'no-search'，默认参数为'mo-search'
BREAKING CHANGE: delete searchable and add searchType
> fix(select): searchable => searchType

- src/components/table/demo/TableScroll.stories.tsx
- src/components/table/style/index.less
> fix(table): style bug on Firefox

- package.json
- src/components/banner/__tests__/__snapshots__/Banner.spec.js.snap
- src/components/button/__tests__/__snapshots__/button.test.js.snap
- src/components/checkbox/__tests__/__snapshots__/checkbox.test.js.snap
- src/components/checkbox/__tests__/__snapshots__/group.test.js.snap
- src/components/drawer/__tests__/__snapshots__/drawer.test.js.snap
- src/components/input/__tests__/__snapshots__/input.test.js.snap
- src/components/menu/__tests__/__snapshots__/menu.test.js.snap
- src/components/modal/__test__/__snapshots__/staticFunc.test.js.snap
- src/components/modal/__test__/__snapshots__/stepModal.test.js.snap
- src/components/pagination/__test__/__snapshots__/Pagination.test.js.snap
- src/components/progress/__tests__/__snapshots__/Progress.test.js.snap
- src/components/search-bar/__tests__/__snapshots__/searchbar.test.js.snap
- src/components/select/__tests__/__snapshots__/Select.test.js.snap
- src/components/steps/__test__/__snapshots__/steps.test.js.snap
- src/components/table/__test__/__snapshots__/Table.test.js.snap
- src/components/toast/__tests__/index.test.js
- src/components/tree-select/__tests__/__snapshots__/tree-select.test.js.snap
- src/components/tree/__tests__/__snapshots__/Tree.test.js.snap
- src/components/upload/__tests__/__snapshots__/actions.test.js.snap
- src/components/upload/__tests__/__snapshots__/preview.test.js.snap
- src/components/upload/__tests__/__snapshots__/upload.test.js.snap
- yarn.lock
BREAKING CHANGE: set @gio-design/icons and @gio-design/tokens as peer dependencies.
> feat: peer depend gio-design/icons gio-design/tokens

- src/components/select/OptionsList/OptionItem.tsx
- src/components/select/OptionsList/index.tsx
- src/components/select/Select.stories.tsx
- src/components/select/Select.tsx
- src/components/select/Selector/index.tsx
- src/components/select/__tests__/Select.test.js
- src/components/select/hooks/useCacheOption.ts
- src/components/select/interface.ts
- src/components/select/style/index.less
- src/components/select/utils.tsx
fix: 
1. disabled状态下不应该显示close
2. 修改select默认颜色为black 6
3. 区分keydown与click针对optionitem的hover状态处理
feat:1.新增参数innerInputPlaceholder:单独设置searchType为inner的placeholder
> fix(select): disabled closeComponent

- src/components/tooltip/Tooltip.tsx
- src/components/tooltip/interface.ts
These components:
- tooltip
- popover
- popconfirm
- dropdown
> feat: replace getTooltipContainer with getContainer

- src/components/tree-select/TreeSelect.stories.tsx
- src/components/tree-select/style/index.less
修复tree-select组件 gio-select-clear的样式问题
> fix(tree-select): 修复tree-select组件的样式问题

- src/components/select/OptionsList/index.tsx
- src/components/select/Select.tsx
- src/components/select/style/index.less
> fix(select): select search normal not focus

- src/components/avatar/style/index.less
relate https://github.com/growingio/gio-design-tokens/pull/86
> feat(avatar): update avatar style

- src/components/cascader/search-bar.tsx
> fix(cascader): fix search clear

- src/components/select/Selector/index.tsx
select mode='string' selector ellipsis error
> fix(select): select mode=string ellipsis error

- jest.config.js
- sonar-project.properties
- src/components/list-pro/Group.tsx
- src/components/list-pro/List.stories.tsx
- src/components/list-pro/Sortable/SortableItem.tsx
- src/components/list-pro/Sortable/index.tsx
- src/components/list-pro/Sortable/template.tsx
- src/components/list-pro/core.tsx
- src/components/list-pro/drag.tsx
- src/components/list-pro/index.ts
- src/components/list-pro/interface.ts
- src/components/list-pro/list.tsx
- src/components/list-pro/normal.tsx
- src/components/list-pro/option.tsx
- src/components/list-pro/style/base.less
- src/components/list-pro/style/index.ts
- src/components/list-pro/style/option.less
- src/components/list-pro/style/sort.less
- src/components/list-pro/utils/withGroupedOptions.tsx
使用方式：
```
import List from '@gio-design/components/es/components/list-pro';
```
> feat: add list pro component

- src/components/page/Page.tsx
- src/components/page/index.ts
- src/index.ts
使用：
```
import { Page, PageProps } from '@gio-design/components';
```
> fix(page): fix page export and add component type

- src/components/dropdown/Dropdown.mdx
- src/components/dropdown/Dropdown.stories.tsx
- src/components/time-picker/index.tsx
- src/components/time-picker/style/index.less
- src/components/time-picker/style/picker.less
- src/components/tree/style/index.less
timepicker文字及icon 颜色，居中对齐问题。
tree  文字背景框icon 水平对齐
dropdown 文档修改
upload 和pagination。未出现问题
> fix(many components): some components centered question resolved

- src/components/input/Password.tsx
- src/components/input/__tests__/__snapshots__/input.test.js.snap
- src/components/input/style/index.less
修复了 input-content 颜色black-6 ，
password 眼睛状态错误
> fix(input): input-content 颜色black-6 ，眼睛状态错误

- src/components/select/OptionsList/OptionItem.tsx
- src/components/select/style/index.less
tooltip show error
tooltip参数显示错误及样式问题
fix #975
> fix(select): tooltip and style

- src/components/loading/Loading.stories.tsx
- src/components/loading/style/index.less
add parentheses in loading/style/index.less
> fix(loading): add parentheses in loading/index.less

- src/components/table/FilterPopover.tsx
- src/components/table/Table.tsx
- src/components/table/Title.tsx
- src/components/table/__test__/TableFilter.test.js
- src/components/table/hook/usePagination.tsx
- src/components/table/interface.ts
BREAKING CHANGE: dataSource reference change will reset pagination status
> fix(table): if columns or data changed, status reset

- src/components/modal/style/modal.less
根据设计师要求 调整弹窗底部按钮间距为8px
https://www.figma.com/file/ZIYRsKMYnXJBastapZCVKt/GrowingIO-Design-System?node-id=0%3A16184
> fix(modal): update modal style

- src/components/button/Button.stories.tsx
- src/components/button/__tests__/__snapshots__/button.test.js.snap
- src/components/button/__tests__/button.test.js
- src/components/button/button.tsx
- src/components/button/interfaces.tsx
- src/components/button/style/index.less
- src/components/button/style/mixin.less
- src/components/link/Link.stories.tsx
- src/components/link/Link.tsx
- src/components/link/interface.ts
- src/components/link/style/index.less
- src/components/select/style/index.less
- src/components/table/FilterPopover.tsx
BREAKING CHANGE: delete link button，replace by Link；update Button and Link styles
> feat(button、link): button、link重构（暂时不合并，合并时找我）

- CHANGELOG.md
- VERSION.md
- package.json
> docs(release): version 21.6.0 changelog

- src/components/select/OptionsList/OptionItem.tsx
- src/components/select/style/index.less
解决select 的option第一项不应有margin-top问题
> style(select): style error(暂不合并)

- jest.config.js
- sonar-project.properties
- src/components/page/ForbiddenSVG.tsx
- src/components/page/InternalServerErrorSVG.tsx
- src/components/page/NotFoundSVG.tsx
- src/components/page/Page.mdx
- src/components/page/Page.stories.tsx
- src/components/page/Page.tsx
- src/components/page/__tests__/Page.test.tsx
- src/components/page/interfaces.ts
- src/components/page/style/index.less
> feat(page): add not found and internal server error page

- package.json
- yarn.lock
Reverts growingio/gio-design#1140
> revert: chore(deps): bump rc-upload from 3.2.0 to 4.3.1

- .husky/pre-commit
- src/components/page/style/index.less
- src/date-picker/style/index.less
- src/date-range-picker/style/index.less
- src/date-selector/style/index.less
- src/selector/style/index.less
The components are:
- Page
- DatePicker
- DateRangePicker
- DateSelector
- Selector
> fix: fix the prefix name of components' style

- src/components/steps/Step.tsx
- src/components/steps/style/index.less
修改steps组件样式：1.灰色横线中间不出现缝隙；2.当无副标题时，高度调整为40px，有副标题时，高度调整为50px。
> feat(steps): update steps style

- src/components/upload/FolderSVG.tsx
- src/components/upload/Upload.tsx
- src/components/upload/__tests__/upload.test.js
- src/components/upload/interface.ts
- src/components/upload/style/index.less
- src/components/upload/triggers/DragTrigger.tsx
upload组件drag模式下调整folder图片并支持调整未选择上传时占位的图片尺寸
> feat(upload): add iconSize prop

- src/components/modal/Modal.stories.tsx
- src/components/modal/style/modal.less
修改modal组件padding
支持组件自定义位置和宽高，当弹窗高度固定时，弹窗内部滚动，最大高度为浏览器高度-200px
> feat(modal): modify modal style

- src/selector/Selector.tsx
- src/selector/__test__/Selector.test.tsx
- src/selector/demos/Selector.mdx
- src/selector/demos/Selector.stories.tsx
- src/selector/index.ts
- src/selector/interfaces.ts
- src/selector/style/index.less
Remove min and max height for overlay.
> feat(selector): add allowClear prop to disable clear

- CHANGELOG.md
- VERSION.md
- package.json
> docs(release): version 21.8.4 change log

- src/components/upload/Preview.tsx
- src/components/upload/Upload.tsx
- src/components/upload/__tests__/__snapshots__/preview.test.js.snap
- src/components/upload/__tests__/upload.test.js
> fix(upload): fix the prevent file upload

- src/components/select/OptionsList/OptionItem.tsx
- src/components/select/style/index.less
- src/components/select/utils.tsx
> fix(select): align center

- src/list-picker/style/index.less
- src/selector/Selector.tsx
Fix list picker css class specificity.
fix #1205
> feat(selector): do not allow clear when disabled

- .storybook/preview.js
- jest.config.js
- package.json
- sonar-project.properties
- src/date-picker/DatePicker.tsx
- src/date-picker/__test__/DatePicker.test.tsx
- src/date-picker/demos/DatePicker.stories.tsx
- src/date-picker/interfaces.ts
- src/date-picker/locales/en-US.ts
- src/date-picker/locales/zh-CN.ts
- src/locales/en-US.ts
- src/locales/zh-CN.ts
- yarn.lock
https://user-images.githubusercontent.com/3879776/131102033-3759c44c-6183-4a8f-afb5-411a7fcb1aef.mov
> feat(locale): date picker support english

- src/table/demos/RowExpandWithFixedColumn.tsx
- src/table/demos/Table.stories.tsx
- src/table/interface.ts
- src/table/style/index.less
fix the expandable style with fixed columns
> fix(table): fix expandable style

- src/components/input/style/index.less
BREAKING CHANGE: change input size small height from 32px to 30px
> fix(input): change input size small height from 32px to 30px

- src/components/upload/Preview.tsx
- src/components/upload/Upload.stories.tsx
- src/components/upload/Upload.tsx
- src/components/upload/__tests__/Preview.test.tsx
- src/components/upload/__tests__/Upload.test.tsx
- src/components/upload/interface.ts
- src/components/upload/style/index.less
- src/components/upload/triggers/DragTrigger.tsx
1. add defaultFileList prop
2. add onReSelect prop
> feat(upload): support defaultFileList

- src/components/select/style/index.less
https://growingio.atlassian.net/browse/PI-37749   
when select component  selected, the selected item should be weighed,
tickets :  https://growingio.atlassian.net/browse/PI-37749
> fix(select) : add selected css font-weight:medium

- src/components/card/__tests__/Card.test.tsx
- src/components/pagination/Pagination.tsx
- src/components/pagination/demos/Pagination.stories.tsx
- src/components/pagination/style/index.less
- src/table/__test__/Table.test.tsx
> fix(pagination): fix pagination style

- src/components/select/Select.tsx
fix: Select.tsx onListSelect function add searchType 'normal' and invoke clearInput
> fix: Select.tsx add searchType 'normal' and invoke clearInput

- src/components/cascader/index.tsx
fix onVIsibleChange not trigger when select
> fix(cascader): fix onVisibleChange not trigger

- src/popconfirm/PopConfirm.tsx
- src/popconfirm/demos/PopConfirm.stories.tsx
- src/popconfirm/index.ts
- src/popconfirm/interface.ts
- src/popconfirm/style/index.less
- src/popconfirm/style/index.ts
- src/popover/Popover.tsx
- src/popover/interface.ts
- src/popover/style/index.less
- src/tooltip/Tooltip.tsx
> feat(Confirm): add confirm component

- src/popover/Popover.tsx
- src/popover/demos/Popover.stories.tsx
- src/popover/interface.ts
某些时候无法正常显示popover, 比如说:overfilow:hidden
> [popover]: render Portal

- src/cascader/Cascader.tsx
- src/cascader/demos/Cascader.stories.tsx
- src/cascader/index.tsx
- src/cascader/interfance.ts
- src/list-picker/demos/List-picker.stories.tsx
- src/list-picker/listPicker.tsx
- src/list-picker/style/index.less
- src/list/List.tsx
- src/list/hooks/useCacheOptions.ts
- src/list/inner/CascaderItem.tsx
- src/list/inner/baseItem.tsx
- src/list/interfance.ts
- src/list/style/index.less
- src/popover/Popover.tsx
- src/select/demos/Select.stories.tsx
- src/select/index.tsx
popover:fix position error
listpicker: mulitple confim
> fix(popover): fix position error

- src/input/style/index.less
> fix(style): update InputButton styles

- src/date-picker/interfaces.ts
- src/date-range-picker/interfaces.ts
- src/list/inner/CascaderItem.tsx
- src/list/interfance.ts
- src/popover/Popover.tsx
- src/popover/demos/Popover.stories.tsx
- src/popover/demos/PopoverPage.tsx
- src/popover/interface.ts
- src/popover/style/index.less
- src/tooltip/interface.ts
Reverts growingio/gio-design#1527
> Revert "feat(popover): popover 不再对触发元素包裹 div；popover 默认挂载到 body 上"

- src/list-picker/interfance.ts
- src/list-picker/listPicker.tsx
- src/list-picker/style/index.less
- src/list/List.tsx
- src/list/inner/CascaderItem.tsx
- src/list/style/index.less
- src/list/util.ts
- src/select/Select.tsx
- src/select/interface.ts
collection:1. listProps prefix 2. OptionPros prefix 3. <Item prefix>
> fix(list-picker): improve context collection capabilities

- src/cascader/Cascader.tsx
- src/cascader/demos/Cascader.stories.tsx
- src/list/List.tsx
- src/list/hooks/useCacheOptions.ts
- src/popover/style/index.less
onChange(val?:string | string[]) =====> onChange(val?:string|string[],options:OptionProps) => void
> [cascader]:onChange method change

- src/popover/Popover.tsx
1. updateVisible method error
2. poporn style error
> fix(popover): fix popover updateVisible method

- src/input/InputButton.tsx
- src/list-picker/style/index.less
- src/list/inner/CascaderItem.tsx
- src/list/style/index.less
- src/popover/Popover.tsx
- src/popover/demos/Popover.stories.tsx
- src/popover/interface.ts
- src/popover/style/index.less
- src/select/Select.tsx
- src/utils/hooks/useControlledState.ts
1. new offset attribute
2. inputButton 去除外层span (由于外层span高度会导致一些问题)
3. 根据offset来设置上下左右距离
4. visible 使用 useControledValue来控制
> fix(popover): refactor offset and add offset attribute

- src/input/InputButton.tsx
- src/popover/style/index.less
- src/tooltip/demos/Tooltip.stories.tsx
> fix(InputButton): add title for InputButton

- src/index.ts
> fix(collapse):add collapse export

- src/list-picker/Recent.tsx
- src/list-picker/demos/List-picker.stories.tsx
- src/list/Selection.tsx
解决 mode === 'mutiple' render 的问题  Recent仅可用于 单选模式
> fix(list-picker): fix Recent multiple error

- src/dropdown/style/index.less
- src/list-picker/style/index.less
- src/list/Empty.tsx
- src/list/Item.tsx
- src/list/List.tsx
- src/list/Selection.tsx
- src/list/context.tsx
- src/list/demos/List.stories.tsx
- src/list/inner/CascaderItem.tsx
- src/list/inner/CheckboxItem.tsx
- src/list/inner/baseItem.tsx
- src/list/interfance.ts
- src/list/util.ts
empty 判断规则：当下层 Item 没有任何一个的时候，则会判断为empty
需要注意的是：
现在无法判断empty是这种结构
```jsx
<selection>{(context) => { /** some code */}}</selection>
```
> fix(list-picker): fix list-picker empty error

- src/legacy/filter-picker/components/FilterList/Expression/FilterCondition/index.tsx
- src/legacy/table/style/index.less
> fix(table): fix legacy table of style

- src/modal/Modal.tsx
footer参数未使用时，提供默认footer
提供footer参数时，优先使用footer，footer值为null，undefined时不显示footer
>  fix(footer):fix default footer

- src/select/Select.tsx
> fix(select): attr autoWidth default false

- src/input/style/index.less
> fix(input): resolve input autofill style issue

- src/modal/style/index.less
- src/switchGroup/style/index.less
switch 最左和最右选中带圆角
Modal close icon 对齐
> fix(switch, modal): fix style

- src/list-picker/Recent.tsx
- src/list/List.tsx
> fix(list-picker): recent component add filter methods

- src/popover/style/index.less
This reverts commit b2425f6d41f43fc7f0f454ab67621b71c752fa34.
> revert(popover): revert #1681

- src/cascader/Cascader.tsx
- src/list-picker/demos/List-picker.stories.tsx
- src/list-picker/interfance.ts
- src/list-picker/listPicker.tsx
- src/list/Empty.tsx
- src/list/List.tsx
- src/list/Selection.tsx
- src/list/context.tsx
- src/list/demos/List.stories.tsx
- src/list/inner/CascaderItem.tsx
- src/list/interfance.ts
- src/list/locales/en-US.ts
- src/list/locales/zh-CN.ts
- src/select/Select.tsx
- src/select/demos/Select.stories.tsx
- src/select/interface.ts
> fix(list): support empty

- src/select/Select.tsx
- src/select/interface.ts
select组件不支持model模式
select组件不支持多选
> fix(select): fix select model prop error

- src/date-picker/Picker.tsx
- src/date-range-picker/Picker.tsx
- src/time-picker/TimePicker.tsx
set active status on InputButton when visible
> feat(date-picker, time-picker): set active status on InputButton when visible

- src/input/Input.tsx
- src/input/style/index.less
> fix(input): -webkit-appearance: none

- src/table/ResizableTable.tsx
- src/table/Table.tsx
- src/table/Title.tsx
- src/table/demos/Table.stories.tsx
- src/table/hook/useFilter.tsx
- src/table/hook/usePagination.tsx
- src/table/hook/useSorter.tsx
- src/table/index.ts
- src/table/interface.ts
- src/table/style/index.ts
- src/table/utils.ts
This reverts commit cb32a9bc2da0c2193b60e2398cfb53a2c804655a.
> revert: #1774

- src/collapse/style/index.less
> fix(collapse): remove margin-right in the icon

- src/pagination/Pagination.tsx
- src/pagination/RowsSelector.tsx
- src/pagination/demos/Pagination.stories.tsx
- src/pagination/hooks/usePagination.ts
- src/pagination/interface.ts
> fix(pagination): trigger onChange and go to first page when pageSize or total were changed

- jest.config.js
- package.json
- yarn.lock
Unit test 执行时间从 `2m2s` 降低到 `56s`
> test: replace ts-jest with @swc/jest

- src/past-time-picker/PastTimePicker.tsx
- src/past-time-picker/demos/PastTimePicker.stories.tsx
- src/past-time-picker/interfaces.ts
- src/static-past-time-picker/AbsoluteRangePicker.tsx
- src/static-past-time-picker/StaticPastTimePicker.tsx
- src/static-past-time-picker/interfaces.ts
> feat(past-time-picker): new feature onRangeSelect

- src/static-past-time-picker/AbsoluteRangePicker.tsx
fix Pastimepicker defaultViewDates display error
> fix(AbsoluteRangePicker): fix AbsoluteRangePicker defaultViewDates error

- src/list/inner/CascaderItem.tsx
- src/popover/Popover.tsx
- src/popover/context.ts
增加sign 判断嵌套结构的 content click，用来支持渲染到body上的 content
> fix(list): list cascader-item on Document click error

- src/popover/Popover.tsx
modify default value of `hideDelay` and make it equal to `delay`
> fix(popover): modify default value of `hideDelay`

- .storybook/index.less
- src/page/demos/Page.stories.tsx
- src/page/demos/PagePage.tsx
- src/page/index.ts
- src/skeleton/Image.tsx
- src/skeleton/demos/Skeleton.stories.tsx
- src/skeleton/demos/SkeletonPage.tsx
- src/tabs/demos/Tabs.stories.tsx
- src/tabs/demos/TabsPage.tsx
- src/typography/demos/Text.stories.tsx
- src/typography/demos/TextPage.tsx
- src/typography/demos/Title.stories.tsx
- src/typography/demos/TitlePage.tsx
- src/typography/title.tsx
- src/upload/demos/Upload.stories.tsx
- src/upload/demos/UploadPage.tsx
- src/upload/interface.ts
- src/upload/triggers/InputTrigger.tsx
> docs(upload): improve upload component docs

- src/list-picker/Trigger.tsx
- src/list-picker/demos/List-picker.stories.tsx
- src/list-picker/interface.ts
- src/list-picker/listPicker.tsx
- src/list-picker/style/index.less
- src/list/List.tsx
- src/list/demos/List.stories.tsx
- src/list/inner/CheckboxItem.tsx
- src/list/interface.ts
- src/list/util.ts
feat:新增 onMultipleOverflow方法，当多选达到max时，触发
fix:1. 修复 label显示问题 2. 修复checkboxItem的prefix和suffix显示问题 3. 修复list-picker tirgger suffix 属性监听错误
> fix(list): when list/list-picker multiple max, trigger onMultipleOverflow

- src/date-picker/demos/DatePicker.stories.tsx
- src/static-date-picker/DatePicker.tsx
> fix(date-picker): fix datepicker month/year view can not select error

- src/static-date-picker/DatePicker.tsx
> fix(date-range-picker): fix panel interaction error

- src/static-date-picker/StaticDatePicker.tsx
> fix(static-date-range-picker): fix panel interaction error

- src/popover/Popover.tsx
> fix(popover): the alternative axis check be enabled

- src/drawer/Drawer.tsx
- src/drawer/demos/Drawer.stories.tsx
- src/drawer/demos/DrawerPage.tsx
- src/drawer/interfaces.ts
Signed-off-by: vermilionAnd <zhujiahong@growingio>
> fix(drawer): size->fixed (attribute change)

- src/list/DragItem.tsx
- src/list/Selection.tsx
- src/list/__tests__/DragList.test.tsx
- src/list/__tests__/Empty.test.tsx
- src/list/__tests__/List.test.tsx
- src/list/__tests__/ListItem.test.tsx
- src/list/__tests__/Selection.test.tsx
- src/list/__tests__/VirtualList.test.tsx
- src/list/__tests__/hooks.test.tsx
- src/list/__tests__/util.test.tsx
- src/list/context.tsx
- src/list/demos/List.stories.tsx
- src/list/hooks/useCacheOptions.ts
- src/list/inner/CascaderItem.tsx
- src/list/inner/CheckboxItem.tsx
> test(list): add test case

- src/table/FilterList.tsx
- src/table/FilterPopover.tsx
- src/table/ResizableTable.tsx
- src/table/Table.tsx
- src/table/__tests__/ResiziableTable.test.tsx
- src/table/__tests__/Table.Sort.test.tsx
- src/table/__tests__/Table.expand.test.tsx
- src/table/__tests__/Table.filter.test.tsx
- src/table/__tests__/Table.pagination.test.tsx
- src/table/__tests__/Table.rowSelection.test.tsx
- src/table/__tests__/Table.test.tsx
- src/table/demos/Table.stories.tsx
- src/table/demos/sorting/Sorting.stories.tsx
- src/table/hook/useSelection.tsx
> test(table): add  test cases of Table

- src/input/style/index.less
- src/layout/style/index.less
- src/utils/composeRef.ts
- set layout flex-basis:auto
- set input::placeholder line-height:revert
> fix(layout): layout and input incompatable in firefox

- src/steps/Step.tsx
- src/steps/Steps.tsx
- src/steps/__tests__/Steps.test.tsx
- src/steps/demos/Steps.stories.tsx
- src/steps/demos/StepsPage.tsx
- src/steps/demos/demo.less
- src/steps/index.ts
- src/steps/interface.ts
- src/steps/style/index.less
- refector codes
- fix some bugs
- remove some Step props
> fix(steps): fix some steps bugs and add test cases

- src/checkbox/demos/Checkbox.stories.tsx
- src/checkbox/style/index.less
- src/list/style/index.less
> fix(list): fix multiple list checkbox style error

- src/list-picker/listPicker.tsx
- src/static-date-picker/__tests__/index.test.tsx
[在非受控情况下开启allowClear,点击清除Icon的时候无效](https://github.com/growingio/gio-design/commit/ab4626ab1bf853d9f152200741d7eb62167b18bf)
> fix(listPicker): 修复在非受控情况下开启allowClear,点击清除Icon的时候无效

- src/date-picker/Picker.tsx
- src/past-time-picker/PastTimePicker.tsx
- src/time-picker/TimePicker.tsx
- src/utils/timeHelper.ts
* feat(past-time-picker): 增加“显示绝对事件”特性
Co-authored-by: YanHui <yanhui@growingio.com>
> feat(past-time-picker): 增加“显示绝对时间”特性 (#2138)

- src/table/FilterList.tsx
- src/table/FilterPopover.tsx
- src/table/Title.tsx
- src/table/demos/Table.stories.tsx
- src/table/interface.ts
/**
* 单选开关 默认false
*/
singleSelect?: boolean;
/**
* 搜索选项开关
*/
filterSearchEnable?: boolean;
/**
* 单选时传默认值, 不传则为filters首项
*/
singleSelectDefaultValue?: string;
> feat(table): table column add singleSelect boolean params

- src/static-past-time-picker/locales/en-US.ts
> fix : 修改本月翻译
